import { useCallback, useMemo, useState } from 'react';
import { useFocusEffect, useLocalSearchParams, useRouter } from 'expo-router';
import { FlatList, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { FlashcardEditor } from '@/components/flashcard-editor';
import { Fonts } from '@/constants/theme';
import { useTheme } from '@/hooks/use-theme';
import { answerSuggestions, makeReadingTest, questionFromPassage, sourceHasTest, type StudySource } from '@/learning/reading-tests';
import type { CardInput } from '@/learning/flashcards';
import { listStudySources } from '@/storage/reading-tests-repository';
import { listLearningCards } from '@/storage/learning-cards-repository';

export default function ReadingTests() {
  const colors = useTheme(), router = useRouter(), params = useLocalSearchParams<{ annotation?: string; book?: string; group?: string }>();
  const [sources, setSources] = useState<StudySource[]>([]), [collections, setCollections] = useState<{ id: string; name: string }[]>([]), [keys, setKeys] = useState<(string | null | undefined)[]>([]);
  const [collection, setCollection] = useState(''), [search, setSearch] = useState(''), [pendingOnly, setPendingOnly] = useState(true), [error, setError] = useState('');
  const [selected, setSelected] = useState<StudySource | null>(null), [phrase, setPhrase] = useState(''), [group, setGroup] = useState(params.group ?? ''), [paste, setPaste] = useState(false), [text, setText] = useState(''), [label, setLabel] = useState('');
  const [savedGroup, setSavedGroup] = useState('');
  const [draft, setDraft] = useState<CardInput | undefined>(), [loading, setLoading] = useState(true);
  const choose = useCallback((source: StudySource) => { setSelected(source); setPhrase(answerSuggestions(source.text)[0] ?? ''); setGroup(params.group || source.group); setError(''); }, [params.group]);
  const reload = useCallback(async () => { try { const [data, cards] = await Promise.all([listStudySources(), listLearningCards(true)]); setSources(data.sources); setCollections(data.collections); setKeys(cards.map(c => c.sourceKey)); setError(''); if (params.annotation) { const source = data.sources.find(s => s.id === `annotation:${params.annotation}`); if (source) choose(source); } } catch { setError('Reading could not load. Try again.'); } finally { setLoading(false); } }, [params.annotation, choose]);
  useFocusEffect(useCallback(() => { void reload(); }, [reload]));
  const visible = useMemo(() => sources.filter(s => (!params.book || s.bookId === params.book) && (!collection || s.collectionIds.includes(collection)) && (!pendingOnly || !sourceHasTest(s.id, keys)) && `${s.label} ${s.text}`.toLocaleLowerCase().includes(search.toLocaleLowerCase())), [sources, collection, pendingOnly, keys, search, params.book]);
  const styles = useMemo(() => StyleSheet.create({ safe: { flex: 1, backgroundColor: colors.background }, content: { padding: 20, paddingBottom: 110, gap: 16 }, row: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 }, title: { fontFamily: Fonts.bold, fontSize: 28, color: colors.text }, text: { fontFamily: Fonts.sans, fontSize: 16, lineHeight: 24, color: colors.text }, muted: { fontFamily: Fonts.sans, fontSize: 12, lineHeight: 19, color: colors.textSecondary }, card: { padding: 18, borderWidth: 1, borderColor: colors.line, borderRadius: 16, backgroundColor: colors.backgroundElement, gap: 12 }, button: { padding: 14, minHeight: 48, borderRadius: 12, backgroundColor: colors.backgroundSelected }, active: { backgroundColor: colors.accentSoft }, input: { padding: 14, borderWidth: 1, borderColor: colors.line, borderRadius: 12, fontFamily: Fonts.sans, fontSize: 16, color: colors.text } }), [colors]);
  const button = (title: string, onPress: () => void, active = false) => <Pressable key={title} accessibilityRole="button" onPress={onPress} style={[styles.button, active && styles.active]}><Text style={styles.text}>{title}</Text></Pressable>;
  const build = () => { if (!selected) return; try { setDraft(makeReadingTest(selected, phrase, group)); setError(''); } catch (e) { setError(e instanceof Error ? e.message : 'Check your passage.'); } };
  return <SafeAreaView edges={['top']} style={styles.safe}>{selected || paste ? <ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={styles.content}>
    {button('‹ Reading catch-up', () => { setSelected(null); setPaste(false); setError(''); })}<Text style={styles.title}>{selected ? 'Turn an idea into a test' : 'Study something you read'}</Text>
    {selected ? <><Text style={styles.muted}>{selected.label}</Text><Text selectable style={styles.text}>{selected.text}</Text><Text style={styles.muted}>Choose the important fact or phrase to recall. Suggestions come directly from the passage; choose one that makes a useful test.</Text><View style={styles.row}>{answerSuggestions(selected.text).map(p => button(p, () => setPhrase(p), p === phrase))}</View><TextInput accessibilityLabel="Phrase to hide" value={phrase} onChangeText={setPhrase} style={styles.input} placeholder="Exact phrase to hide" placeholderTextColor={colors.textSecondary} /><Text style={styles.text}>Learning group</Text><TextInput accessibilityLabel="Learning group" value={group} onChangeText={setGroup} style={styles.input} /><Text style={styles.muted}>Use the same group for related books and ideas. You can rewrite the draft into a why, how or application question before saving.</Text>{button('Preview fill-in-the-gap test', build, true)}{questionFromPassage(selected, group) ? button('Preview question & answer', () => setDraft(questionFromPassage(selected, group) ?? undefined)) : null}</> : <><TextInput accessibilityLabel="Reading source title" value={label} onChangeText={setLabel} placeholder="Book, article or topic" placeholderTextColor={colors.textSecondary} style={styles.input} /><TextInput accessibilityLabel="Text to study" value={text} onChangeText={setText} multiline maxLength={3500} placeholder="Paste a passage or your reading notes…" placeholderTextColor={colors.textSecondary} style={[styles.input, { minHeight: 200, textAlignVertical: 'top' }]} />{button('Choose what to recall', () => { if (text.trim().length < 10 || !label.trim()) { setError('Add a source title and a short passage first.'); return; } choose({ id: `text:${label.trim()}:${text.trim()}`, bookId: null, label: label.trim(), text: text.trim(), note: '', group: label.trim(), collectionIds: [], createdAt: new Date().toISOString() }); }, true)}</>}
    {error ? <Text accessibilityRole="alert" style={styles.text}>{error}</Text> : null}
  </ScrollView> : <FlatList data={visible} keyExtractor={s => s.id} contentContainerStyle={styles.content} ListHeaderComponent={<View style={{ gap: 14 }}>
    {button('‹ Flashcards', () => router.back())}<Text style={styles.title}>Reading catch-up</Text>{savedGroup ? button(`Test saved · Study ${savedGroup} →`, () => router.push({ pathname: '/learning/cards/study', params: { mode: 'due', topic: savedGroup } }), true) : null}<Text style={styles.muted}>Build tests from your saved highlights and notes. Pick an idea, check the draft, then study it in a learning group.</Text>{button('＋ Paste reading or notes', () => { setPaste(true); setError(''); })}<ScrollView horizontal contentContainerStyle={styles.row}>{button('All collections', () => setCollection(''), !collection)}{collections.map(c => button(c.name, () => setCollection(c.id), c.id === collection))}</ScrollView><TextInput accessibilityLabel="Search reading" value={search} onChangeText={setSearch} placeholder="Search books or passages" placeholderTextColor={colors.textSecondary} style={styles.input} />{button(pendingOnly ? 'Needs a test · show all' : 'All passages · show without tests', () => setPendingOnly(!pendingOnly))}<Text style={styles.muted}>{visible.length} passages{params.book ? ' from this book' : ''}</Text>{error ? button('Try again', () => { void reload(); }) : null}
  </View>} ListEmptyComponent={<Text style={styles.text}>{loading ? 'Loading your reading…' : pendingOnly && sources.length > 0 ? 'No passages need a test in this selection. Show all passages to make another test, or study your group.' : 'No passages here yet. Save a highlight in Books, import your Kindle highlights, or paste a passage above.'}</Text>} renderItem={({ item }) => <View style={styles.card}><Text style={styles.muted}>{item.label}{sourceHasTest(item.id, keys) ? ' · Test saved' : ''}</Text><Text numberOfLines={5} style={styles.text}>{item.text}</Text>{button('Build a test', () => { choose(item); if (collection) setGroup(collections.find(c => c.id === collection)?.name ?? item.group); })}</View>} />}
    <FlashcardEditor visible={!!draft} initial={draft} onClose={() => setDraft(undefined)} onSaved={saved => { if (saved?.sourceKey) setKeys(old => [...old, saved.sourceKey]); setSavedGroup(saved?.deckName ?? ''); setSelected(null); setPaste(false); }} />
  </SafeAreaView>;
}
