import type { CoreSkillSeedNode, CoreSkillTreeSeed } from './core-skill-seeds';
import type { SkillDimension } from './types';

type AbilityInput = [key: string, title: string, prerequisites: string[], practice: string, success: string, dimension?: SkillDimension];

const ability = ([key, title, prerequisiteKeys, practicePrompt, successCriteria, dimension = 'procedural']: AbilityInput): CoreSkillSeedNode => ({
  key, title, prerequisiteKeys, practicePrompt, successCriteria, dimension,
  description: `Perform ${title.toLocaleLowerCase()} reliably in a realistic situation.`,
});

const tree = (key: string, title: string, description: string, abilities: AbilityInput[]): CoreSkillTreeSeed => ({ key, title, description, nodes: abilities.map(ability) });

export const FOCUSED_SKILL_TREE_SEEDS: CoreSkillTreeSeed[] = [
  tree('customer-research', 'Customer research', 'Discover what people need from behaviour rather than polite opinions.', [
    ['segment', 'Define a research segment', [], 'Choose one behavioural segment and write inclusion and exclusion criteria.', 'Two recruiters select the same target participants from the criteria.', 'conceptual'],
    ['interview-guide', 'Design a non-leading interview', ['segment'], 'Write ten questions about a participant’s most recent relevant experience without pitching a solution.', 'Every major question asks for events, actions, costs or evidence rather than hypothetical preference.'],
    ['interview', 'Run a customer interview', ['interview-guide'], 'Conduct and record a 30-minute interview, following concrete details instead of the script.', 'The notes reveal sequence, workaround, stakes, decision participants and exact language.'],
    ['synthesise', 'Code evidence into patterns', ['interview'], 'Code five interviews by trigger, job, pain, workaround, outcome and quote.', 'Each pattern is supported by multiple observations and contradictory cases remain visible.'],
    ['problem-rank', 'Rank customer problems', ['synthesise'], 'Score observed problems by frequency, severity, budget, urgency and access.', 'The winner has traceable behavioural evidence and a stated reason the alternatives lose.', 'conditional'],
    ['test-demand', 'Test willingness to act', ['problem-rank'], 'Ask target customers for a costly commitment such as time, data, introduction or payment.', 'The result records an action or refusal, not enthusiasm alone.', 'transfer'],
    ['research-brief', 'Produce a decision-ready research brief', ['test-demand'], 'Write a one-page recommendation with evidence, uncertainty and the next cheapest test.', 'A product decision changes because of the evidence and has a named falsification condition.', 'transfer'],
  ]),
  tree('product-management', 'Product management', 'Turn customer and business evidence into valuable product decisions.', [
    ['outcome', 'Define a product outcome', [], 'Translate a vague feature request into a user behaviour and business result.', 'The outcome is measurable without assuming a particular solution.', 'conceptual'],
    ['opportunity', 'Map an opportunity space', ['outcome'], 'Build an opportunity tree from interviews, analytics and support evidence.', 'Every opportunity traces to evidence and is distinct from a proposed feature.'],
    ['prioritise', 'Prioritise product opportunities', ['opportunity'], 'Rank opportunities by reach, value, confidence, effort and strategic fit.', 'The ranking exposes assumptions and explains what will not be pursued.', 'conditional'],
    ['hypothesis', 'Write a falsifiable product hypothesis', ['prioritise'], 'State user, change, expected behaviour, mechanism, metric and failure threshold.', 'A result can clearly support or reject the hypothesis.'],
    ['prototype', 'Test a solution before building', ['hypothesis'], 'Create the cheapest realistic prototype and run five task-based sessions.', 'Observed task behaviour reveals a specific design change or a stop decision.'],
    ['slice', 'Define a thin vertical release', ['prototype'], 'Specify the smallest end-to-end release that produces the target outcome.', 'A real user can complete the whole job and excluded scope is explicit.'],
    ['review', 'Run an evidence-led product review', ['slice'], 'Compare adoption, outcome, quality and qualitative evidence with the prediction.', 'The review chooses scale, revise or stop and assigns the next test.', 'transfer'],
  ]),
  tree('sales', 'Sales', 'Diagnose fit, create conviction and win mutually valuable commitments.', [
    ['account', 'Qualify a target account', [], 'Research one account’s situation, likely pain, authority, timing and current alternative.', 'The qualification cites evidence and states a clear disqualifier.', 'conceptual'],
    ['outreach', 'Write relevant outbound outreach', ['account'], 'Write a short message connecting a specific trigger to a credible useful outcome.', 'The recipient can understand relevance in ten seconds and the ask is low-friction.'],
    ['discovery', 'Run a diagnostic discovery call', ['outreach'], 'Ask about current process, consequences, priority, stakeholders and decision path.', 'The buyer speaks most of the time and a quantified problem or no-fit conclusion emerges.'],
    ['demo', 'Demonstrate value in context', ['discovery'], 'Show only the workflow that addresses the buyer’s stated problem using their scenario.', 'The buyer can explain how the product changes their current process.'],
    ['objection', 'Resolve a real objection', ['demo'], 'Restate an objection, identify its type, test the concern and respond with evidence.', 'The concern becomes a resolved condition, next test or honest disqualification.', 'discrimination'],
    ['proposal', 'Build a decision-ready proposal', ['objection'], 'Write scope, value, proof, responsibilities, price, risk controls and next steps.', 'All decision-makers can compare the proposal with doing nothing.'],
    ['close', 'Close with mutual commitment', ['proposal'], 'Ask directly for the decision and agree dated implementation obligations on both sides.', 'The result is a signed commitment or a specific, evidence-based loss reason.', 'transfer'],
  ]),
  tree('marketing', 'Marketing', 'Position an offer, create demand and measure profitable acquisition.', [
    ['audience', 'Define a reachable audience', [], 'Define a segment by situation, behaviour, pain and channel rather than demographics alone.', 'The audience can be found and the exclusion boundary is clear.', 'conceptual'],
    ['positioning', 'Create differentiated positioning', ['audience'], 'Map alternatives and write who the offer is for, category, value and unique proof.', 'A target customer can distinguish it from the closest alternative.'],
    ['message', 'Build a message hierarchy', ['positioning'], 'Write a primary promise, three supporting benefits, proof and objection responses.', 'Every claim connects to an audience need and has appropriate evidence.'],
    ['creative', 'Produce channel-native creative', ['message'], 'Create three substantially different executions for one channel and audience.', 'Each execution earns attention, communicates value and has one action.'],
    ['campaign', 'Design a measurable campaign', ['creative'], 'Define objective, audience, offer, channel, budget, funnel events and stop conditions.', 'Results can be attributed well enough to decide whether to continue.'],
    ['funnel', 'Diagnose a conversion funnel', ['campaign'], 'Calculate stage conversion and segment the largest drop by source and audience.', 'The diagnosis identifies a bottleneck and a testable mechanism, not merely a low metric.', 'conditional'],
    ['growth-loop', 'Build a compounding growth loop', ['funnel'], 'Model how one acquired user creates an input that attracts or retains another.', 'The loop has a measurable cycle, limiting factor and evidence of repeatability.', 'transfer'],
  ]),
  tree('business-strategy', 'Business strategy', 'Make coherent choices about where to compete and how to win.', [
    ['diagnosis', 'Diagnose the strategic challenge', [], 'Reduce a complex situation to the few forces that explain outcomes.', 'The diagnosis distinguishes causes from symptoms and predicts what happens without action.', 'conceptual'],
    ['industry', 'Analyse industry structure', ['diagnosis'], 'Map buyers, suppliers, substitutes, entrants, rivals and profit pools.', 'The map explains where bargaining power and durable margins reside.'],
    ['capability', 'Identify distinctive capabilities', ['diagnosis'], 'Compare resources and activities with competitors for value, rarity and replicability.', 'Claimed strengths are evidenced by outcomes and linked to customer value.'],
    ['choice', 'Choose where to play', ['industry', 'capability'], 'Select customer, need, geography, channel and scope while naming exclusions.', 'The arena concentrates advantage and explicitly rejects plausible alternatives.', 'conditional'],
    ['advantage', 'Design a reinforcing advantage', ['choice'], 'Map activities that jointly lower cost, increase willingness to pay or strengthen a moat.', 'The activities reinforce one another and are difficult to copy as a system.'],
    ['scenario', 'Stress-test strategy with scenarios', ['advantage'], 'Test the strategy against three plausible changes in demand, technology or competition.', 'Leading indicators and contingent responses are defined for each scenario.'],
    ['kernel', 'Write an executable strategy kernel', ['scenario'], 'Combine diagnosis, guiding policy, coordinated actions, metrics and ownership.', 'Near-term actions address the diagnosed challenge and reveal whether the strategy works.', 'transfer'],
  ]),
  tree('operations', 'Operations & process design', 'Create reliable, measurable systems that improve flow and quality.', [
    ['map-flow', 'Map work end to end', [], 'Observe one process and map trigger, steps, queues, decisions, rework and completion.', 'The map reflects actual work and includes wait time and failure paths.', 'conceptual'],
    ['measure', 'Measure operational performance', ['map-flow'], 'Define demand, throughput, lead time, work in progress, quality and cost for the process.', 'Measures have clear start/end points and can be reproduced.'],
    ['constraint', 'Identify the system constraint', ['measure'], 'Use flow data and observation to locate what limits total throughput.', 'Changing the named constraint predicts a larger system effect than optimising elsewhere.', 'conditional'],
    ['standard', 'Design standard work', ['constraint'], 'Document the best current method, inputs, quality checks and escalation boundaries.', 'A trained peer performs the process consistently from the standard.'],
    ['quality', 'Prevent defects at the source', ['standard'], 'Analyse one recurring defect and add a control where the error originates.', 'The control detects or prevents the cause before downstream rework.'],
    ['capacity', 'Plan capacity under variability', ['measure', 'quality'], 'Model demand, service time, utilisation, buffers and peak scenarios.', 'The plan meets a service target without relying on average demand alone.'],
    ['improve', 'Run a closed-loop improvement', ['constraint', 'capacity'], 'Change one process variable, measure before and after, and standardise or revert.', 'Throughput, quality, time or cost improves without hidden harm elsewhere.', 'transfer'],
  ]),
  tree('management', 'Management & leadership', 'Create clarity, capability and accountable ownership through other people.', [
    ['expectations', 'Set clear outcome expectations', [], 'Define outcome, rationale, constraints, quality bar and deadline for one responsibility.', 'The owner can restate success and make the first decision independently.', 'conceptual'],
    ['one-on-one', 'Run a useful one-to-one', ['expectations'], 'Hold a conversation led by the report’s priorities, obstacles, feedback and growth.', 'The meeting produces candour, a decision or a concrete support action.'],
    ['feedback', 'Give behaviour-changing feedback', ['one-on-one'], 'Describe situation, observable behaviour, impact and the next desired repetition.', 'The recipient understands the change and has a near-term chance to practise it.'],
    ['delegate', 'Delegate real ownership', ['expectations'], 'Assign an outcome with authority, constraints, check-ins and escalation triggers.', 'The owner can act without hidden approvals and retains responsibility for the result.'],
    ['coach', 'Coach through a performance gap', ['feedback', 'delegate'], 'Diagnose whether a gap comes from clarity, skill, will, resources or system design.', 'The intervention matches the cause and includes observable practice evidence.', 'conditional'],
    ['team-system', 'Design a team operating system', ['delegate'], 'Define goals, roles, decision rights, information cadence and conflict mechanisms.', 'Routine decisions occur at the right level and important work has one owner.'],
    ['change', 'Lead an organisational change', ['coach', 'team-system'], 'Explain the case, involve affected people, sequence adoption and monitor behaviour.', 'Target behaviour changes and resistance produces adaptation rather than silence.', 'transfer'],
  ]),
  tree('negotiation', 'Negotiation', 'Prepare, create trades and reach sound agreements under tension.', [
    ['interests', 'Separate positions from interests', [], 'For a disagreement, list each stated position, underlying interest and constraint.', 'At least one option can satisfy an interest without accepting the original position.', 'conceptual'],
    ['batna', 'Build and value a BATNA', ['interests'], 'Define the best alternative, reservation point and cost of delay using evidence.', 'You can reject an inferior agreement without bluffing.'],
    ['discover', 'Discover the other side’s priorities', ['interests'], 'Ask calibrated questions about goals, constraints, process and differently valued terms.', 'You identify at least two tradable differences without demanding confidential data.'],
    ['packages', 'Create multiple equivalent offers', ['batna', 'discover'], 'Design three packages that vary price, timing, scope, risk and support.', 'Each package meets your reservation point and reveals the other side’s priorities.'],
    ['anchor', 'Use and respond to anchors', ['packages'], 'Prepare a justified first proposal and a response to an extreme opposing anchor.', 'The discussion returns to evidence and your planned range rather than emotional concession.', 'conditional'],
    ['close-terms', 'Close complete agreement terms', ['anchor'], 'Confirm scope, owners, dates, contingencies, enforcement and unresolved items in writing.', 'Both sides interpret obligations the same way and foreseeable failure cases are covered.'],
    ['review-deal', 'Review negotiation performance', ['close-terms'], 'Compare preparation, information gained, concessions and outcome with the BATNA.', 'The review identifies one repeatable strength and one behaviour to test next time.', 'transfer'],
  ]),
  tree('project-management', 'Project management', 'Deliver complex outcomes through scope, sequencing, risk and coordination.', [
    ['charter', 'Write a project charter', [], 'Define outcome, rationale, sponsor, scope, constraints, measures and deadline.', 'Stakeholders agree what success includes and excludes.', 'conceptual'],
    ['breakdown', 'Decompose deliverable work', ['charter'], 'Break the outcome into verifiable deliverables and work packages.', 'Every package has an owner and produces an inspectable result.'],
    ['sequence', 'Build a dependency schedule', ['breakdown'], 'Order work by prerequisites, duration, capacity and external lead times.', 'The critical path and schedule assumptions are visible.'],
    ['risk', 'Maintain an active risk register', ['sequence'], 'Identify risks with probability, impact, trigger, mitigation and owner.', 'Top risks have actions before they become issues.', 'conditional'],
    ['status', 'Report decision-ready status', ['sequence', 'risk'], 'Report forecast, progress, variance, risks, decisions and next milestones.', 'A sponsor can intervene without requesting a second explanatory meeting.'],
    ['change-control', 'Control scope changes', ['status'], 'Assess a proposed change against value, schedule, cost, risk and displaced work.', 'The change is accepted, rejected or deferred with consequences recorded.'],
    ['close-project', 'Close and learn from a project', ['change-control'], 'Verify acceptance, transfer ownership, close obligations and run a causal retrospective.', 'Benefits have an owner and lessons change a future template or behaviour.', 'transfer'],
  ]),
  tree('accounting', 'Accounting', 'Record transactions and interpret the financial statements they create.', [
    ['equation', 'Apply the accounting equation', [], 'Classify twenty transactions as changes in assets, liabilities and equity.', 'The equation balances after every transaction.', 'conceptual'],
    ['journal', 'Create balanced journal entries', ['equation'], 'Record sales, purchases, payroll, debt and owner transactions with debits and credits.', 'Every entry balances and uses the correct account type.'],
    ['accrual', 'Apply accrual and matching', ['journal'], 'Record prepaid expense, unearned revenue, receivable and depreciation adjustments.', 'Revenue and expense appear in the period economic activity occurs.'],
    ['statements', 'Prepare financial statements', ['accrual'], 'Produce income statement, balance sheet and cash-flow statement from a trial balance.', 'Statements reconcile and explain the change in cash.'],
    ['reconcile', 'Reconcile an account', ['journal'], 'Reconcile a bank or control account to independent evidence and investigate differences.', 'Every difference is corrected, timed or supported.'],
    ['analyse', 'Analyse accounting ratios', ['statements'], 'Calculate margins, liquidity, leverage, turnover and returns across periods.', 'The analysis connects movements to underlying transactions and operations.', 'conditional'],
    ['controls', 'Design basic financial controls', ['reconcile', 'analyse'], 'Map a financial process and assign approval, custody, recording and review controls.', 'A plausible error or fraud path is prevented or promptly detected.', 'transfer'],
  ]),
  tree('corporate-finance', 'Corporate finance', 'Evaluate investments, funding and capital allocation for an operating business.', [
    ['cash-flow', 'Build free cash flow', [], 'Translate operating forecasts into after-tax cash flow and working-capital needs.', 'Cash flow reconciles with operating assumptions and financing is excluded.', 'conceptual'],
    ['discount-rate', 'Estimate a discount rate', ['cash-flow'], 'Estimate cost of debt, cost of equity and weighted cost of capital with explicit inputs.', 'The rate matches currency, risk and cash-flow definition.'],
    ['npv', 'Evaluate an investment with NPV', ['discount-rate'], 'Model initial cost, scenario cash flows, terminal value and net present value.', 'The recommendation is based on value created, not payback alone.'],
    ['sensitivity', 'Run sensitivity and scenario analysis', ['npv'], 'Vary the most uncertain operating and financing assumptions.', 'Break-even values and downside exposure are visible.', 'conditional'],
    ['funding', 'Compare financing choices', ['discount-rate'], 'Compare debt, equity and internal funding on cost, control, flexibility and distress risk.', 'The choice fits cash-flow resilience and strategic constraints.'],
    ['valuation', 'Value a business', ['npv', 'sensitivity'], 'Triangulate DCF, comparable multiples and transaction logic.', 'Differences between methods are explained by assumptions rather than averaged blindly.'],
    ['allocate', 'Recommend capital allocation', ['funding', 'valuation'], 'Rank reinvestment, acquisition, debt repayment and distributions under scenarios.', 'The plan preserves survival and directs capital to the highest risk-adjusted use.', 'transfer'],
  ]),
  tree('economics', 'Economics', 'Reason about incentives, trade-offs, markets and policy consequences.', [
    ['opportunity-cost', 'Identify opportunity cost', [], 'For a real choice, name the best forgone alternative and value what is sacrificed.', 'The cost reflects the next-best option rather than sunk spending.', 'conceptual'],
    ['marginal', 'Reason at the margin', ['opportunity-cost'], 'Compare the incremental benefit and cost of one more unit or action.', 'The decision changes at an explicit threshold.'],
    ['supply-demand', 'Model supply and demand shifts', ['marginal'], 'Draw and explain a market response to a demand or supply shock.', 'Price and quantity movements distinguish shifts from movement along a curve.'],
    ['elasticity', 'Use elasticity in a decision', ['supply-demand'], 'Estimate how quantity responds to price and calculate revenue implications.', 'The recommendation matches the sign and magnitude of elasticity.'],
    ['externality', 'Analyse an externality', ['marginal'], 'Map private and social costs or benefits and compare corrective mechanisms.', 'The proposed intervention targets the wedge and includes likely unintended effects.', 'conditional'],
    ['macro', 'Interpret a macroeconomic change', ['supply-demand'], 'Trace an inflation, interest-rate or unemployment change through households and firms.', 'The explanation separates nominal from real effects and states uncertainty.'],
    ['policy', 'Evaluate an economic policy', ['externality', 'macro'], 'Compare policy options by incentives, distribution, implementation and second-order effects.', 'The recommendation names winners, losers, assumptions and evidence that would change it.', 'transfer'],
  ]),
  tree('investing', 'Investing', 'Research, value and size investments while managing permanent-loss risk.', [
    ['objective', 'Write an investment mandate', [], 'Define goal, horizon, liquidity, risk capacity, benchmark and prohibited actions.', 'A portfolio decision can be accepted or rejected from the mandate.', 'conceptual'],
    ['quality', 'Analyse business quality', ['objective'], 'Assess economics, durability, reinvestment, governance and capital intensity.', 'Claims are supported by multi-year evidence and compared with competitors.'],
    ['thesis', 'Write a falsifiable investment thesis', ['quality'], 'State why expectations are wrong, the value driver, timeline and disconfirming evidence.', 'The thesis differs from a company description and can be proven wrong.'],
    ['value', 'Estimate intrinsic value', ['thesis'], 'Value the asset under bear, base and bull operating scenarios.', 'The range traces to cash-flow assumptions and avoids false precision.'],
    ['risk', 'Map permanent-loss risks', ['thesis'], 'List business, balance-sheet, valuation, governance and thesis risks with indicators.', 'Risk analysis includes how loss occurs, not volatility alone.', 'conditional'],
    ['size', 'Size a portfolio position', ['value', 'risk'], 'Choose position size using conviction, downside, correlation and liquidity.', 'A thesis failure cannot jeopardise the portfolio mandate.'],
    ['review', 'Run an investment review', ['size'], 'Compare new evidence with thesis, valuation and predefined sell conditions.', 'Action follows evidence rather than price movement or narrative attachment.', 'transfer'],
  ]),
  tree('algebra-functions', 'Algebra & functions', 'Manipulate symbolic relationships and use functions to model change.', [
    ['expressions', 'Simplify algebraic expressions', [], 'Simplify ten expressions using distributive, exponent and fraction rules.', 'Equivalent values are confirmed by substitution.', 'procedural'],
    ['linear', 'Solve linear equations and inequalities', ['expressions'], 'Solve mixed linear equations and inequalities, including variables on both sides.', 'Solutions satisfy the original statement and inequality direction is correct.'],
    ['systems', 'Solve systems of equations', ['linear'], 'Solve three systems algebraically and interpret intersections.', 'Each ordered solution satisfies every equation.'],
    ['function', 'Interpret function notation', ['linear'], 'Evaluate, compose and invert simple functions from formula, table and graph.', 'Inputs, outputs, domain and range are correctly distinguished.', 'conceptual'],
    ['quadratic', 'Analyse quadratic functions', ['function', 'expressions'], 'Move between standard, factored and vertex form and identify roots and extrema.', 'Features agree across algebra and graph.'],
    ['exponential', 'Model exponential change', ['function'], 'Fit and compare growth or decay models from real data.', 'Rate, multiplier and time unit are interpreted correctly.', 'conditional'],
    ['model', 'Build an algebraic model', ['systems', 'quadratic', 'exponential'], 'Translate a real constraint problem into functions and solve it.', 'Units, domain and residual error are checked against reality.', 'transfer'],
  ]),
  tree('probability', 'Probability', 'Represent uncertainty, dependence and belief updates correctly.', [
    ['sample-space', 'Construct a sample space', [], 'Enumerate outcomes for compound experiments using tables or trees.', 'Outcomes are mutually exclusive and collectively exhaustive.', 'conceptual'],
    ['rules', 'Apply probability rules', ['sample-space'], 'Solve union, intersection and complement problems.', 'Answers obey bounds and double counting is handled.'],
    ['conditional', 'Compute conditional probability', ['rules'], 'Solve conditional cases using tables, trees and formulas.', 'Conditioning changes the denominator correctly.'],
    ['bayes', 'Update with Bayes’ rule', ['conditional'], 'Solve a diagnostic base-rate problem and explain posterior odds.', 'Base rate, likelihood and posterior are not confused.'],
    ['random-variable', 'Work with random variables', ['rules'], 'Calculate expected value and variance for discrete outcomes.', 'The expected value matches a long-run weighted average.'],
    ['distributions', 'Choose a probability distribution', ['random-variable'], 'Match binomial, normal, Poisson and exponential models to scenarios.', 'Assumptions and parameter meanings fit the generating process.', 'conditional'],
    ['decision', 'Use probability in a decision', ['bayes', 'distributions'], 'Build a decision tree with uncertain outcomes and information value.', 'The action maximises stated utility under transparent assumptions.', 'transfer'],
  ]),
  tree('statistics', 'Statistics', 'Learn from samples while representing uncertainty and assumptions honestly.', [
    ['describe', 'Describe a distribution', [], 'Summarise centre, spread, shape and outliers for a dataset.', 'The chosen summaries fit the distribution and preserve important variation.', 'conceptual'],
    ['sampling', 'Reason about sampling variation', ['describe'], 'Simulate repeated samples and compare sample statistics with the population.', 'The explanation distinguishes population, sample and sampling distribution.'],
    ['interval', 'Construct and interpret an interval', ['sampling'], 'Calculate a confidence interval and explain its repeated-sampling meaning.', 'The interpretation avoids assigning probability to a fixed parameter.'],
    ['test', 'Run a hypothesis test', ['sampling'], 'State hypotheses, check assumptions, calculate evidence and report effect size.', 'Conclusion separates statistical evidence from practical importance.'],
    ['regression', 'Fit and diagnose a regression', ['describe'], 'Fit a linear model and inspect residuals, leverage and uncertainty.', 'Coefficients have contextual meaning and diagnostics qualify the claim.'],
    ['multiple', 'Control for multiple comparisons', ['test'], 'Analyse a set of related tests using a declared correction or hierarchical plan.', 'The false-positive risk is addressed before selecting interesting results.', 'conditional'],
    ['report', 'Write a reproducible statistical conclusion', ['interval', 'regression', 'multiple'], 'Report data, method, assumptions, uncertainty, limitations and decision relevance.', 'Another analyst can reproduce the result and identify what is not supported.', 'transfer'],
  ]),
  tree('data-analysis', 'Data analysis', 'Turn messy data into reproducible, decision-relevant evidence.', [
    ['question', 'Frame an analytical question', [], 'Translate a stakeholder request into population, measure, comparison and decision.', 'The question determines what data and method are needed.', 'conceptual'],
    ['audit', 'Audit a dataset', ['question'], 'Profile schema, types, ranges, missingness, duplicates and provenance.', 'Every material quality issue is quantified and assigned a treatment.'],
    ['transform', 'Build a reproducible data transform', ['audit'], 'Create a documented sequence from raw data to analysis-ready table.', 'Running the process twice yields the same data without manual edits.'],
    ['explore', 'Explore patterns without fooling yourself', ['transform'], 'Visualise distributions, segments and relationships while logging hypotheses after viewing.', 'Exploratory findings are labelled and obvious confounders are checked.'],
    ['metric', 'Define a trustworthy metric', ['question', 'audit'], 'Specify numerator, denominator, unit, window, exclusions and data owner.', 'Two analysts calculate the same value from the definition.'],
    ['communicate', 'Build a decision-focused analysis', ['explore', 'metric'], 'Present the decision, answer, evidence, uncertainty and recommended action.', 'The audience can act without reading every exploratory step.'],
    ['monitor', 'Productionise an analytical signal', ['communicate'], 'Define refresh, validation, threshold, owner and response for a recurring metric.', 'A broken input is detected and a threshold breach triggers a named action.', 'transfer'],
  ]),
  tree('causal-inference', 'Experiments & causal inference', 'Determine whether an intervention changes an outcome.', [
    ['causal-question', 'State a causal estimand', [], 'Define treatment, outcome, population, time and comparison for a real question.', 'The target quantity is distinct from a descriptive association.', 'conceptual'],
    ['dag', 'Draw a causal diagram', ['causal-question'], 'Map plausible causes, confounders, mediators and colliders.', 'Adjustment choices follow paths in the diagram rather than convenience.'],
    ['randomise', 'Design a randomised experiment', ['causal-question'], 'Specify unit, assignment, treatment, outcome, power and analysis plan.', 'Randomisation can be implemented and the primary analysis is predeclared.'],
    ['validity', 'Diagnose experiment validity', ['randomise'], 'Check balance, attrition, noncompliance, interference and measurement changes.', 'Threats are quantified and their direction is discussed.', 'conditional'],
    ['observational', 'Choose an observational design', ['dag'], 'Select matching, regression discontinuity, difference-in-differences or instruments for a case.', 'The identification assumption is explicit and plausibly testable.'],
    ['heterogeneity', 'Estimate treatment heterogeneity', ['validity'], 'Define a small set of pre-specified subgroup effects and shrink noisy estimates.', 'Claims distinguish genuine variation from multiple-testing noise.'],
    ['decision', 'Turn causal evidence into a decision', ['observational', 'heterogeneity'], 'Combine effect, uncertainty, cost, scale and external validity.', 'The recommendation states where the result transfers and what monitoring remains.', 'transfer'],
  ]),
  tree('programming', 'Programming foundations', 'Express, test and debug reliable computational procedures.', [
    ['values', 'Use values, variables and types', [], 'Write small expressions over strings, numbers, booleans and collections.', 'Outputs and type errors match predictions.', 'conceptual'],
    ['control', 'Use control flow correctly', ['values'], 'Solve branching and iteration exercises including empty and boundary cases.', 'Every path terminates and edge cases have expected output.'],
    ['functions', 'Design small functions', ['control'], 'Decompose a transformation into named functions with explicit inputs and outputs.', 'Each function has one responsibility and can be tested independently.'],
    ['structures', 'Choose data structures', ['values', 'functions'], 'Implement the same lookup or aggregation with alternative structures and compare.', 'The chosen structure fits access, ordering and update requirements.', 'conditional'],
    ['errors', 'Handle errors explicitly', ['functions'], 'Validate inputs and represent recoverable versus programmer errors.', 'Invalid input cannot silently create plausible wrong output.'],
    ['tests', 'Write useful automated tests', ['functions', 'errors'], 'Write examples, boundaries and property-style tests before fixing a bug.', 'The tests fail for the bug and pass only after the cause is fixed.'],
    ['program', 'Build a complete command-line program', ['structures', 'tests'], 'Build a tool that reads input, transforms it, persists output and reports failures.', 'A new user completes the task and corrupted input is handled safely.', 'transfer'],
  ]),
  tree('software-engineering', 'Software engineering', 'Design, change and operate maintainable production software.', [
    ['requirements', 'Turn requirements into contracts', [], 'Write inputs, outputs, invariants, failure behaviour and acceptance examples.', 'Ambiguous cases become explicit decisions before implementation.', 'conceptual'],
    ['boundaries', 'Design module boundaries', ['requirements'], 'Partition a feature by responsibility, data ownership and change frequency.', 'Dependencies point toward stable contracts and duplicated truth is avoided.'],
    ['change', 'Make a safe incremental change', ['boundaries'], 'Implement one vertical slice with tests and a reversible rollout path.', 'Existing behaviour remains verified and the new path is observable.'],
    ['review', 'Review code for structural risk', ['change'], 'Inspect a change for correctness, state, concurrency, trust boundaries and operability.', 'Feedback identifies causal failure modes and actionable fixes.', 'discrimination'],
    ['debug', 'Debug from evidence', ['change'], 'Reproduce a fault, narrow the failing boundary, test hypotheses and verify the cause.', 'The fix removes the cause and a regression test proves it.'],
    ['reliability', 'Design for operational reliability', ['boundaries', 'debug'], 'Add timeouts, retries, idempotency, limits, logs and recovery to a workflow.', 'Partial failures are detected and cannot corrupt durable state.'],
    ['operate', 'Ship and operate a service', ['review', 'reliability'], 'Release with metrics, alerts, rollback criteria and a post-release check.', 'The service meets its objective and an on-call responder can diagnose failure.', 'transfer'],
  ]),
  tree('databases', 'Databases', 'Model, query and protect durable application data.', [
    ['entities', 'Model entities and identity', [], 'Define entities, stable identifiers, attributes and lifecycle for a domain.', 'The model distinguishes identity from mutable labels.', 'conceptual'],
    ['relations', 'Model relationships and constraints', ['entities'], 'Represent one-to-one, one-to-many and many-to-many relationships with integrity rules.', 'Impossible relationships are rejected by the model.'],
    ['query', 'Write correct relational queries', ['relations'], 'Write filtering, joining, grouping and window queries against sample data.', 'Results match hand-worked examples including missing values.'],
    ['normalise', 'Normalise duplicated data', ['relations'], 'Decompose a table with update anomalies and state functional dependencies.', 'Each fact has one authoritative storage location.'],
    ['transaction', 'Use transactions and concurrency control', ['query'], 'Design a multi-step update and demonstrate what happens under concurrent execution.', 'Invariants hold under failure and competing writers.', 'conditional'],
    ['index', 'Design and verify an index', ['query', 'normalise'], 'Read a query plan, add an index and measure its write and read trade-offs.', 'The plan changes as predicted and production-like latency improves.'],
    ['migrate', 'Run a safe schema migration', ['transaction', 'index'], 'Plan expand, backfill, verify and contract phases with rollback.', 'Old and new application versions coexist during deployment without data loss.', 'transfer'],
  ]),
  tree('web-apis', 'Web & APIs', 'Build interoperable web interfaces with explicit contracts and failure handling.', [
    ['http', 'Reason about HTTP', [], 'Trace requests through method, URL, headers, body, status and cache behaviour.', 'Method semantics and status codes match the operation.', 'conceptual'],
    ['contract', 'Design a resource API', ['http'], 'Specify resources, schemas, identifiers, pagination, errors and versioning.', 'A client can integrate without undocumented assumptions.'],
    ['validate', 'Validate untrusted input', ['contract'], 'Implement boundary validation for types, ranges, size and authorization context.', 'Malformed and unauthorised requests fail safely with useful errors.'],
    ['auth', 'Implement authentication and authorization', ['validate'], 'Model identity, session/token lifecycle and per-resource permissions.', 'A user cannot access another user’s resource by changing an identifier.'],
    ['resilience', 'Build a resilient API client', ['contract'], 'Handle timeouts, retries, backoff, pagination and idempotency.', 'Transient failure recovers without duplicate side effects.'],
    ['observe', 'Instrument an API', ['resilience'], 'Record latency, errors, saturation and correlation IDs without leaking secrets.', 'A failed request can be traced across boundaries.'],
    ['ship', 'Ship an end-to-end web integration', ['auth', 'observe'], 'Deliver a client-server workflow with contract tests and recovery behaviour.', 'A real user completes the task and failures are diagnosable.', 'transfer'],
  ]),
  tree('cybersecurity', 'Cybersecurity fundamentals', 'Recognise threats and design proportionate controls around valuable assets.', [
    ['assets', 'Identify assets and security goals', [], 'List sensitive assets and required confidentiality, integrity and availability.', 'Each asset has an owner and consequence of compromise.', 'conceptual'],
    ['boundaries', 'Map trust boundaries', ['assets'], 'Draw users, systems, data flows and where trust level changes.', 'Every external input and privileged action crosses a named boundary.'],
    ['threats', 'Build a threat model', ['boundaries'], 'Enumerate attacker goals, capabilities and abuse paths for one workflow.', 'Threats are concrete paths tied to assets rather than generic labels.'],
    ['controls', 'Select proportionate controls', ['threats'], 'Map preventive, detective and recovery controls to top threats.', 'Controls reduce likelihood or impact and their limitations are stated.', 'conditional'],
    ['secrets', 'Manage credentials safely', ['controls'], 'Design creation, storage, least privilege, rotation and revocation for a secret.', 'Secrets never enter source, logs or unencrypted storage.'],
    ['incident', 'Respond to a security incident', ['controls'], 'Run a tabletop covering detection, containment, evidence, recovery and communication.', 'Roles, decision thresholds and preserved evidence are clear.'],
    ['verify', 'Verify a security design', ['secrets', 'incident'], 'Test authorization, input handling, dependency and recovery assumptions.', 'High-risk claims have evidence and remaining risk has an owner.', 'transfer'],
  ]),
  tree('ai-fluency', 'AI fluency', 'Choose, direct and evaluate AI systems without surrendering judgment.', [
    ['fit', 'Recognise AI-suitable tasks', [], 'Classify tasks by ambiguity, error cost, verification and data sensitivity.', 'The choice distinguishes AI assistance from deterministic automation.', 'conceptual'],
    ['brief', 'Write an effective AI brief', ['fit'], 'Specify objective, context, constraints, examples, rubric and output format.', 'A reviewer can evaluate the answer without guessing intent.'],
    ['context', 'Provide useful context safely', ['brief'], 'Select the minimum relevant source material and remove unnecessary sensitive data.', 'The model has enough evidence while excluded data cannot affect the task.'],
    ['verify', 'Verify an AI answer', ['brief', 'context'], 'Check claims against primary sources, recompute critical results and inspect omissions.', 'Consequential claims have independent evidence.', 'discrimination'],
    ['iterate', 'Improve output through critique', ['verify'], 'Ask for failure analysis against the rubric, then revise inputs or constraints.', 'The second output fixes identified defects without introducing worse ones.'],
    ['workflow', 'Design a human-AI workflow', ['iterate'], 'Assign generation, deterministic checks, human review and escalation boundaries.', 'Errors are caught before consequence and responsibility remains explicit.'],
    ['measure', 'Measure AI workflow value', ['workflow'], 'Compare quality, time, cost and failure rate against the previous process.', 'Adoption is justified by measured net value rather than novelty.', 'transfer'],
  ]),
  tree('ai-engineering', 'AI engineering & automation', 'Build evaluated AI workflows that are reliable enough for production use.', [
    ['contract', 'Define an AI output contract', [], 'Specify schema, allowed evidence, abstention and quality rubric for one task.', 'Outputs are machine-validated and uncertain cases have a safe state.', 'conceptual'],
    ['retrieval', 'Build grounded retrieval', ['contract'], 'Chunk, index, retrieve and cite a small authoritative corpus.', 'Answers use relevant passages and unsupported claims are detectable.'],
    ['tools', 'Design safe tool use', ['contract'], 'Define tool parameters, permissions, confirmation rules and idempotent actions.', 'Invalid or repeated calls cannot cause uncontrolled side effects.'],
    ['evals', 'Build a representative evaluation set', ['retrieval'], 'Create normal, edge, adversarial and abstention cases with expected judgments.', 'The set predicts meaningful real-world failure better than demo examples.'],
    ['orchestrate', 'Orchestrate a bounded agent workflow', ['tools', 'evals'], 'Implement state, step limits, retries, checkpoints and human escalation.', 'The workflow terminates, exposes its trace and recovers from tool failure.'],
    ['observe', 'Monitor AI behaviour in production', ['orchestrate'], 'Log inputs, decisions, latency, cost, quality signals and privacy-safe traces.', 'Regressions are detected and traceable to model, prompt, data or tool changes.'],
    ['release', 'Release an evaluated AI feature', ['observe'], 'Run offline evals, staged rollout, red-team cases and rollback checks.', 'Release thresholds pass and production evidence confirms the intended value.', 'transfer'],
  ]),
  tree('clear-writing', 'Clear writing', 'Write precise, structured prose that helps a reader understand and act.', [
    ['reader', 'Define reader and purpose', [], 'Name the reader’s prior knowledge, question, stakes and desired action.', 'Every planned section serves the same reader decision.', 'conceptual'],
    ['claim', 'Write a precise main claim', ['reader'], 'Write one sentence stating the answer, scope and important qualification.', 'The claim can be disagreed with and does not hide behind abstraction.'],
    ['evidence', 'Support claims with evidence', ['claim'], 'Pair each material claim with source, example, data or explicit reasoning.', 'Readers can distinguish evidence from inference.'],
    ['structure', 'Structure for reader questions', ['claim', 'evidence'], 'Outline sections in the order a sceptical reader needs them.', 'Each section has one job and earns the next.'],
    ['paragraph', 'Build coherent paragraphs', ['structure'], 'Revise paragraphs to contain a controlling idea, support and transition.', 'No sentence is orphaned or doing another paragraph’s job.'],
    ['edit', 'Edit for precision and economy', ['paragraph'], 'Remove throat-clearing, vague nouns, redundant modifiers and passive evasion.', 'Meaning is preserved with fewer words and clearer agency.'],
    ['publish', 'Produce a decision-ready document', ['edit'], 'Write and user-test a memo, guide or argument with a real reader.', 'The reader accurately summarises it and takes the intended action.', 'transfer'],
  ]),
  tree('public-speaking', 'Public speaking', 'Design and deliver spoken communication that holds attention and changes understanding.', [
    ['audience', 'Diagnose a speaking audience', [], 'Define what the audience knows, believes, fears and needs to do.', 'The talk objective reflects audience change rather than speaker coverage.', 'conceptual'],
    ['message', 'Create one memorable message', ['audience'], 'Write the single sentence listeners should repeat the next day.', 'The sentence is specific, useful and supported by the talk.'],
    ['story', 'Use a story as evidence', ['message'], 'Tell a short scene with character, tension, change and relevance.', 'The story makes the point clearer rather than merely entertaining.'],
    ['structure', 'Structure a spoken narrative', ['message', 'story'], 'Arrange opening, stakes, evidence, objections and close for live attention.', 'A listener can follow without seeing headings.'],
    ['delivery', 'Deliver with vocal and physical control', ['structure'], 'Record a five-minute delivery and review pace, pauses, emphasis and movement.', 'Key points receive emphasis and distracting patterns are reduced.'],
    ['questions', 'Handle audience questions', ['delivery'], 'Practise clarifying, answering briefly, admitting uncertainty and bridging back.', 'Answers address the actual question without defensiveness.'],
    ['live-talk', 'Deliver and improve a live talk', ['questions'], 'Present to a real audience, collect recall and action evidence, then revise.', 'Audience behaviour confirms the objective or identifies a specific change.', 'transfer'],
  ]),
  tree('research-critical-thinking', 'Research & critical thinking', 'Find trustworthy evidence, test claims and form calibrated conclusions.', [
    ['question', 'Form a researchable question', [], 'Turn a broad topic into population, concept, comparison and decision.', 'The question guides inclusion of evidence and admits uncertainty.', 'conceptual'],
    ['search', 'Search systematically', ['question'], 'Build search terms, source types, citation trails and a search log.', 'Relevant contrary evidence has a reasonable chance of being found.'],
    ['source', 'Evaluate source credibility', ['search'], 'Assess proximity, expertise, incentives, method, date and corroboration.', 'Credibility judgments cite source features rather than reputation alone.', 'discrimination'],
    ['argument', 'Map an argument', ['source'], 'Separate claims, reasons, evidence, assumptions, objections and implications.', 'A hidden premise and strongest counterargument are explicit.'],
    ['synthesise', 'Synthesise conflicting evidence', ['argument'], 'Group evidence by mechanism, quality and context instead of source-by-source summary.', 'The synthesis explains disagreement and weights evidence transparently.'],
    ['calibrate', 'Calibrate a conclusion', ['synthesise'], 'State confidence, scope, unresolved uncertainty and what evidence would change it.', 'Strength of language matches strength of evidence.', 'conditional'],
    ['brief', 'Produce an auditable research brief', ['calibrate'], 'Write answer, evidence map, counterevidence, limitations and recommendation.', 'A reader can trace every material claim and reproduce the reasoning.', 'transfer'],
  ]),
  tree('persuasion', 'Persuasion & rhetoric', 'Change minds ethically through audience understanding, argument and credible evidence.', [
    ['belief', 'Map an audience belief', [], 'Identify current belief, supporting experiences, identity stakes and trusted evidence.', 'The map predicts which argument will be resisted and why.', 'conceptual'],
    ['ethos', 'Establish appropriate credibility', ['belief'], 'Choose relevant expertise, transparency and shared values for a message.', 'Credibility supports the claim without substituting status for evidence.'],
    ['frame', 'Frame an issue productively', ['belief'], 'Write three truthful frames emphasising different values or consequences.', 'The chosen frame is relevant and does not conceal material facts.', 'conditional'],
    ['argument', 'Build a sound persuasive argument', ['frame'], 'State claim, evidence, warrant, qualification and rebuttal.', 'The conclusion follows and the strongest objection is answered fairly.'],
    ['emotion', 'Use emotion without manipulation', ['belief', 'argument'], 'Add a concrete human consequence proportionate to the evidence.', 'Emotion increases salience without fabricating certainty or threat.'],
    ['call', 'Design a credible call to action', ['argument'], 'Specify one feasible action, timing, friction reduction and reason to act now.', 'The audience knows exactly what to do and can reasonably do it.'],
    ['test', 'Test persuasive impact', ['emotion', 'call'], 'Deliver variants and measure comprehension, belief and behaviour.', 'Improvement is based on audience evidence rather than speaker preference.', 'transfer'],
  ]),
  tree('visual-design', 'Visual design', 'Create interfaces and graphics with hierarchy, clarity and coherent systems.', [
    ['hierarchy', 'Create visual hierarchy', [], 'Arrange the same content in three ways using size, weight, contrast and position.', 'A viewer identifies primary, secondary and supporting information quickly.', 'conceptual'],
    ['layout', 'Build a consistent layout', ['hierarchy'], 'Create a grid, alignment rules and spacing rhythm for a screen.', 'Elements align intentionally and related spacing is consistent.'],
    ['type', 'Design readable typography', ['hierarchy'], 'Choose type scale, line length, leading and emphasis for dense content.', 'Text remains readable and roles are distinguishable without decoration alone.'],
    ['colour', 'Use colour functionally', ['hierarchy'], 'Define neutral, action, status and accent roles with accessible contrast.', 'Colour meaning is consistent and information survives without colour.'],
    ['component', 'Design reusable components', ['layout', 'type', 'colour'], 'Define one component’s anatomy, states, content rules and variants.', 'The component handles realistic content without one-off exceptions.'],
    ['flow', 'Design an end-to-end user flow', ['component'], 'Prototype a task across entry, action, feedback, error and completion states.', 'A user completes the task and recovers from an injected error.'],
    ['system', 'Build and critique a visual system', ['flow'], 'Apply tokens and components across three screens, then audit inconsistency.', 'The screens feel related and deviations have documented reasons.', 'transfer'],
  ]),
  tree('decision-making', 'Decision making', 'Choose well under uncertainty, bias, trade-offs and limited information.', [
    ['frame', 'Frame the decision correctly', [], 'State decision owner, deadline, objective, constraints and what happens by default.', 'The frame separates the choice from background discussion.', 'conceptual'],
    ['options', 'Generate genuinely different options', ['frame'], 'Create at least five options including delay, experiment and combination.', 'Options differ in mechanism rather than wording.'],
    ['criteria', 'Define decision criteria', ['frame'], 'Weight outcomes, constraints, reversibility and values before scoring options.', 'Criteria do not secretly encode a preferred answer.'],
    ['uncertainty', 'Quantify key uncertainty', ['options', 'criteria'], 'Estimate ranges and probabilities for variables that could reverse the choice.', 'Sensitivity analysis identifies which uncertainty matters most.'],
    ['bias', 'Run a bias pre-mortem', ['uncertainty'], 'Assume the decision failed and identify incentives, blind spots and base rates ignored.', 'At least one mitigation or new test changes the process.', 'discrimination'],
    ['commit', 'Commit with review conditions', ['bias'], 'Choose an option, record rationale, owner, action and evidence-based review trigger.', 'Execution begins and the decision is not casually relitigated.'],
    ['calibrate', 'Learn from decision quality', ['commit'], 'Review process separately from outcome and compare forecasts with results.', 'A specific update improves the next decision process.', 'transfer'],
  ]),
];
