import type { CoreSkillTreeSeed } from './core-skill-seeds';

// Original drills and assessment rubrics. Sources inform the concepts, not an
// endorsement or a claim that this is a validated elite-performance programme.
type Drill = [key: string, title: string, prerequisites: string[], concept: string, exercise: string, criteria: string, repeat: string];
type Resource = { title: string; url: string; when: string };
const tree = (key: string, title: string, description: string, drills: Drill[]): CoreSkillTreeSeed => ({
  key: `marketing-${key}`, title, description,
  nodes: drills.map(([key, title, prerequisiteKeys, description, exercise, criteria, repeat]) => ({
    key, title, prerequisiteKeys, description,
    practicePrompt: `${exercise}\n\nNext repetition: ${repeat}`,
    successCriteria: `${criteria}\n\nMeet every criterion independently before rating clean. Log your output and corrections.`,
    dimension: key === 'capstone' ? 'transfer' : 'procedural',
  })),
});

export const MARKETING_CURRICULA: CoreSkillTreeSeed[] = [
  tree('foundations', 'Marketing foundations', 'Start here. Practice method, customer value, arithmetic, evidence and a first marketing diagnosis.', [
    ['practice', 'Set up a practice loop', [], 'Train an observable ability, compare with a standard, correct the weakest part, then attempt a fresh case. Reading time and direct practice are separate.', 'Choose one real business and a second business for transfer. Spend 15 minutes writing a customer brief without AI or notes; compare it with customer evidence. Log the draft, error and correction using the practice timer.', 'Brief names customer, buying situation, alternative, offer and action. Evidence is separate from assumptions; only active work is logged as practice.', 'Tomorrow reconstruct the brief unaided. Use due reviews in the app; after a clean repetition, change the business. Start with a daily 25-minute block: 5 review, 15 production, 5 feedback.'],
    ['value', 'Map a customer decision', ['practice'], 'Marketing connects customer needs with product, price, distribution and communication. An ad cannot repair every business constraint.', 'Map one recent purchase: trigger, alternatives, evaluation, purchase, use and repeat. Attach an observation to each stage and identify which marketing decision could change it.', 'Six stages grounded in behaviour; at least one product, price, access and communication decision; no invented motives.', 'Map a service purchase, then a B2B purchase involving several people.'],
    ['evidence', 'Separate facts from hypotheses', ['practice'], 'A claim needs a traceable source. Association, customer opinion and a randomised comparison support different conclusions.', 'Collect ten marketing claims. Label each observation, interpretation or causal claim. For each causal claim name a competing explanation and the evidence needed to distinguish it.', 'All sources recorded; no before/after chart described as causal proof; three claims rewritten at the strength their evidence supports.', 'Use ten unfamiliar claims, including one impressive case study with missing denominators.'],
    ['rates', 'Calculate funnel rates', ['value'], 'A rate divides outcomes by the relevant opportunities. Percentage-point change is different from relative change.', 'From 20,000 impressions, 400 visits, 40 leads and 8 sales, calculate each stage rate and total sale rate. Compare a lead rate rising from 10% to 12%. Work by hand, then check in a sheet.', 'Answers: 2%, 10%, 20%, 0.04%; increase is 2 percentage points or 20% relative. Every rate labels its denominator.', 'Generate five new funnels; include a zero denominator and explain why that rate is undefined.'],
    ['economics', 'Calculate contribution and CAC', ['rates'], 'Revenue is not profit. Contribution subtracts variable costs; acquisition cost must specify which costs and which new customers it includes.', 'Model 100 orders at $100, $40 variable cost per order and $2,000 acquisition spend for 50 new customers. Calculate revenue, pre-ad contribution, contribution after ads, paid CAC and ROAS.', 'Answers: $10,000, $6,000, $4,000, $40 and 5x. Fixed costs, refunds and organic acquisition costs are explicitly excluded rather than forgotten.', 'Add refunds and repeat purchases. Reconcile paid CAC with fully loaded blended CAC.'],
    ['objectives', 'Build a metric tree', ['rates', 'economics'], 'Connect a business outcome to controllable inputs; guardrails prevent improving a proxy while damaging the business.', 'Draw revenue as customers × orders per customer × net order value. Add contribution costs. Choose one outcome, two input metrics and two guardrails for the business.', 'Units reconcile; inputs can be acted on; a scenario shows clicks increasing while profit falls.', 'Build the equivalent tree for a subscription or a sales-led service.'],
    ['diagnosis', 'Find the binding constraint', ['evidence', 'objectives'], 'Diagnose before selecting a channel. Low demand, weak offer, inaccessible distribution and poor conversion need different interventions.', 'Write a one-page diagnosis using five facts, three competing explanations and one discriminating next test. Rank actions by expected benefit, confidence and effort with stated assumptions.', 'Recommendation addresses an evidenced constraint; a rival explanation survives; test could change the decision.', 'Use a business with high conversion but little reach, then one with traffic and no sales.'],
    ['capstone', 'Defend a marketing diagnosis', ['diagnosis'], 'Transfer requires a fresh business and external challenge, not a polished retelling of your original case.', 'Analyse your second business without copying the first brief. Give a practitioner or business owner your metric tree, evidence and proposed experiment. Record their strongest objection and revise.', 'Arithmetic reconciles; reviewer feedback recorded verbatim with permission; revision changes a decision or explains why evidence supports keeping it.', 'After a week, diagnose a third category in 45 minutes and compare errors against your first attempt.'],
  ]),
  tree('research', 'Marketing research', 'Customer interviews, observation, surveys, segmentation and evidence synthesis. Bring your foundations brief.', [
    ['question', 'Frame a research decision', [], 'Research should reduce uncertainty about a decision. Begin with the customer brief and facts-versus-hypotheses exercise from Marketing foundations if these are unfamiliar.', 'Write one decision, three unknowns and what different answers would make you do. Select interview, observation, survey or experiment for each unknown.', 'Every unknown changes an action; methods match questions; interviews are not used to estimate market prevalence.', 'Reframe a vague request such as “understand our audience” into a decision about an offer.'],
    ['sample', 'Recruit contrasting customers', ['question'], 'Convenient respondents can hide important differences. Recruitment criteria should be about relevant behaviour, not flattering opinions.', 'Draft a screener and recruitment plan including recent buyers, non-buyers and churned users. State exclusions, consent procedure and likely sampling bias.', 'Criteria are observable; at least three contrasting cases; no claim the sample represents an entire market.', 'Design a plan for a hard-to-reach B2B buying group.'],
    ['interview', 'Ask about a past decision', ['sample'], 'Specific past events reveal context and trade-offs. Leading questions and hypothetical purchase promises are weak evidence.', 'Rewrite ten leading questions. Conduct a 20-minute interview about the last relevant purchase, with permission to take notes. Ask for timeline, alternatives and actual actions.', 'Questions do not pitch the product; five traceable behavioural observations; quotes and interpretations separated.', 'Interview a lost buyer. Practise neutral follow-ups on contradictions rather than defending your idea.'],
    ['observe', 'Observe a real task', ['sample'], 'What people do can differ from what they say. Observe a task without guiding them through the intended solution.', 'Ask a willing participant to compare or purchase a product in a prototype without payment. Record pauses, workarounds, failures and exact task outcome.', 'Task is realistic; no coaching; observations distinguish action from guessed emotion.', 'Use a new participant and a competing experience, keeping the task comparable.'],
    ['code', 'Code evidence into themes', ['interview', 'observe'], 'A theme should be traceable to evidence and should retain disconfirming examples.', 'Code 20 excerpts into triggers, alternatives, barriers and outcomes. Write definitions for each code; ask another reader to independently code five excerpts and resolve disagreements.', 'All excerpts retain source IDs; code definitions distinguish categories; contradictory evidence is included.', 'Apply the codebook to a fresh interview; revise a category only with an explicit reason.'],
    ['survey', 'Build an unbiased survey', ['code'], 'A survey needs comprehensible items, sensible answer options and a sampling plan. Small convenience samples do not establish population percentages.', 'Write six questions for one unresolved theme. Remove double-barrelled wording, add appropriate no-answer options, and pilot with three people who explain each question aloud.', 'Each question measures one thing; response options work; pilot misunderstandings lead to edits; prevalence claims match sampling limits.', 'Reverse the order of answer options and identify possible order effects before a new pilot.'],
    ['segments', 'Form actionable segments', ['code', 'survey'], 'Useful segments differ in needs or behaviour and imply different actions. Demographic descriptions alone may not change a decision.', 'Propose three segments from your evidence. For each list trigger, alternative, value sought, reachable channel and uncertainty. Predict one meaningful difference before collecting more evidence.', 'Segments lead to different decisions; evidence links exist; size and willingness-to-pay guesses are labelled.', 'Test a segment boundary against five new observations and record exceptions.'],
    ['capstone', 'Deliver a research decision memo', ['segments'], 'Research is useful when its evidence changes a decision while preserving uncertainty.', 'For a new category, combine interviews or public behavioural evidence with one observation. Deliver a two-page recommendation, evidence appendix, contradictions and next research question for external review.', 'Reader can trace three recommendations to evidence; no fabricated interviews; limitations stated; reviewer challenges addressed.', 'Return after a real business decision and document which prediction held or failed.'],
  ]),
  tree('positioning', 'Positioning & go-to-market', 'Competitive alternatives, segmentation, positioning, launch and sales enablement.', [
    ['alternatives', 'Map competitive alternatives', [], 'Positioning starts with what buyers would use without you, including manual work or doing nothing. Use the research tree if you cannot support these alternatives.', 'For a real product list five alternatives, the circumstances each wins, switching costs and sources. Include the status quo.', 'Alternatives reflect customer choices, not only similar products; every claimed advantage has evidence.', 'Repeat for a service with no obvious direct competitor.'],
    ['value', 'Prove differentiated value', ['alternatives'], 'A capability matters when it produces a valued outcome that alternatives cannot provide as well in a relevant situation.', 'Build six capability → mechanism → outcome → evidence chains. Cross out unsupported uniqueness. Pick two that matter to a specific buyer.', 'Mechanism explains the benefit; evidence supports relative claims; buyer relevance is documented.', 'Ask a sceptical buyer which chain is irrelevant and revise it.'],
    ['target', 'Select an initial market', ['value'], 'An initial target focuses execution; it is not a claim that other buyers never matter.', 'Compare three candidate markets on urgency, ability to pay, access, alternatives and delivery fit. Estimate size with a bottom-up range, not a single impressive TAM number.', 'Scoring is explained; estimates have sources and ranges; choice changes the product or route to market.', 'Stress-test the choice with acquisition cost doubled and a longer buying cycle.'],
    ['position', 'Write and test positioning', ['target'], 'Connect alternatives, differentiated value, best-fit customers and market category. A positioning statement is an internal choice, not automatically a headline.', 'Write a one-page positioning document and two category frames. Ask three relevant people to explain what it is, for whom and why choose it.', 'Responses recorded without coaching; frame reduces confusion; no unsupported “best” claim.', 'Apply the same framework to a new category without copying the language.'],
    ['message', 'Build a message hierarchy', ['position'], 'Different stakeholders need different evidence while the core promise stays coherent.', 'Write a core promise, three supporting messages and evidence for user, economic buyer and technical evaluator. Turn one into a five-slide sales narrative.', 'Messages agree; each stakeholder concern has proof; narrative explains the status quo and change.', 'Present aloud and revise the first question your listener could not answer.'],
    ['launch', 'Design a launch sequence', ['message'], 'A launch coordinates product readiness, distribution, sales and measurement; a posting calendar alone is insufficient.', 'Draft prelaunch, launch and follow-through milestones with owner, dependency, readiness gate and rollback condition. Include customer feedback and operational capacity.', 'Critical dependencies have owners; customer path is complete; success and stop conditions are measurable.', 'Replan for a two-week delay and half the budget.'],
    ['enablement', 'Build sales enablement', ['message'], 'A good sales asset helps a buyer make a decision and a seller diagnose fit.', 'Create a discovery guide, comparison sheet and objection card. Run a role-play with a sceptical buyer; capture where proof or qualification fails.', 'Comparison is factual and dated; guide asks before pitching; next action and disqualifiers are clear.', 'Repeat with procurement and with a user who lacks buying authority.'],
    ['capstone', 'Defend a go-to-market plan', ['launch', 'enablement'], 'Integrate research, economics and positioning into a plan that can survive contrary evidence.', 'Use a second business to present target, positioning, channel, launch, economics and learning plan to an operator. Document assumptions they reject and revise.', 'Six decisions connect; cost and capacity feasible; external critique changes the plan; success is not defined by impressions alone.', 'Review after a pilot and compare actual demand and conversion with the forecast.'],
  ]),
  tree('brand', 'Brand & consumer behaviour', 'Buying situations, memory, distinctive assets, reach, distribution and brand measurement.', [
    ['situations', 'Map buying situations', [], 'Brands can become easier to recall in relevant buying situations. A claimed psychological bias is not proof it drives this purchase.', 'Collect ten sourced buying situations for one category. Separate occasion, motivation, location and competing alternatives.', 'Situations are specific and supported; no invented universal consumer law.', 'Compare habitual low-involvement buying with a high-stakes B2B purchase.'],
    ['memory', 'Diagnose mental availability', ['situations'], 'Recognition, recall in a buying situation and purchase are distinct outcomes. Brand-memory frameworks are hypotheses to measure in the category.', 'Design an unaided recall exercise for three buying situations, followed by recognition. Pilot the wording; document contamination from showing brand names too early.', 'Unaided questions precede brand exposure; measures and sampling limits clear; recall is not equated with sales.', 'Use a new category and separate current customers from non-customers.'],
    ['assets', 'Audit distinctive assets', ['memory'], 'An asset helps identification when buyers associate it with the brand rather than competitors. Looking attractive is a different test.', 'Inventory colours, shapes, sounds, characters and verbal cues. Design a masked identification task and pilot it with five people as exploratory feedback.', 'Competing brand guesses retained; familiarity and uniqueness distinguished; pilot is not claimed as population validation.', 'Remove the logo from a second asset set and compare recognition errors.'],
    ['reach', 'Plan reach and frequency', ['situations'], 'Repeated exposure to the same people is different from reaching more category buyers. Frequency has costs and context-dependent effects.', 'Compare two plans with the same impressions but different unique reach and frequency. Specify category coverage, placement context and saturation uncertainty.', 'Reach is deduplicated or explicitly estimated; frequency calculation correct; no universal magic frequency assumed.', 'Add overlapping channels and show why their reach cannot simply be added.'],
    ['access', 'Audit physical availability', ['situations'], 'Demand can fail to convert when a product is difficult to find, buy, receive or use.', 'Trace five buying journeys across search, store or marketplace, checkout and fulfilment. Record availability, access friction and missing options.', 'Each issue is observed; fixes have owners; distribution constraints separated from communication problems.', 'Audit a location-based service and an online subscription.'],
    ['system', 'Create a consistent brand system', ['assets', 'access'], 'A brand system makes identification consistent across touchpoints while keeping each execution useful.', 'Create a one-page asset guide and apply it to an ad, landing page, email and package or invoice. Check identification and legibility with another person.', 'Core assets stay recognisable; required information survives small sizes; feedback records mistaken identification.', 'Adapt to a new format without adding unrelated styling.'],
    ['measure', 'Design a brand scorecard', ['reach', 'system'], 'A long-term scorecard needs measures connected to buying behaviour, with time horizons and competing explanations.', 'Specify recall, asset recognition, category penetration and distribution measures. Name sample, cadence, baseline and decision triggered by each.', 'Metrics have denominators; change can be distinguished from sample noise; short-term clicks do not substitute for all brand outcomes.', 'Explain a case where brand indicators improve while sales fall because distribution shrinks.'],
    ['capstone', 'Resolve a brand growth case', ['measure'], 'Use mental and physical availability as diagnostic lenses, not as a substitute for category evidence.', 'Write a fresh case diagnosis integrating buying situations, reach, assets and distribution. Have a marketer challenge it; identify one evidence-based intervention and measurement plan.', 'Both demand and access assessed; external critique saved; proposed effect is testable with a realistic time horizon.', 'Compare a small challenger and a mature brand; explain which priorities differ.'],
  ]),
  tree('offers', 'Offers & pricing', 'Value, unit economics, packaging, price research, elasticity and promotion decisions.', [
    ['costs', 'Build a unit-economics model', [], 'Start with Marketing foundations arithmetic. Separate fixed, variable and acquisition costs before choosing an offer.', 'Create a sheet for a $120 product with $45 variable cost, $15 expected returns/support per sale and $30 CAC. Calculate contribution before and after acquisition, then break-even orders for $3,000 fixed cost.', 'Answers: $60, $30, 100 orders; assumptions visible; formulas update when inputs change.', 'Repeat for a monthly service including churn and support capacity.'],
    ['value', 'Estimate customer value', ['costs'], 'Value depends on the alternative and the buyer’s circumstances. Willingness to pay is not the same as value claimed by the seller.', 'Compare time, money, risk and effort for three alternatives. Build a customer value range with explicit assumptions and identify the most uncertain input.', 'Alternative costs traceable; no double counting benefits; value estimate is not presented as validated willingness to pay.', 'Use a buyer for whom your strongest benefit has no value.'],
    ['package', 'Design coherent packages', ['value'], 'Packages should map to real differences in need or usage rather than arbitrary feature withholding.', 'Design three packages with unit of value, inclusions, boundaries, service cost and migration path. Explain who should not buy each.', 'Every tier has an economic and customer rationale; terms understandable; margins calculated.', 'Remove a feature and predict who changes tier and why.'],
    ['research', 'Investigate price sensitivity', ['package'], 'Stated preferences can diverge from behaviour. Price research needs realistic alternatives and careful interpretation.', 'Write a neutral price interview and a choice exercise with realistic alternatives. Pilot with three people; separate affordability, fairness and value objections.', 'Questions do not lead; choices include no purchase; sample limitations and hypothetical bias explicit.', 'Change the context or alternative and examine how answers move.'],
    ['elasticity', 'Model a price change', ['research'], 'Price affects both margin and demand; a revenue increase can conceal a profit decline.', 'At price $100, cost $60 and 100 units, compare price $90 with 120 units, and price $110 with 90 units. Calculate revenue and contribution before fixed costs.', 'Baseline $10,000/$4,000; discount $10,800/$3,600; increase $9,900/$4,500. Volume assumptions are predictions, not facts.', 'Calculate the volume required for a 10% discount to preserve contribution, then test other margins.'],
    ['promo', 'Evaluate a promotion', ['elasticity'], 'A promotion may shift purchase timing or subsidise existing demand. Evaluate incremental contribution and operational effects.', 'Model a promotion including cannibalisation, pull-forward, returns, fulfilment and new buyers. Compare against a no-promotion scenario and a non-price offer.', 'All incremental costs included; optimistic and pessimistic cases shown; revenue alone does not determine the winner.', 'Repeat for a subscription trial with low conversion and high service costs.'],
    ['test', 'Design an offer test', ['promo'], 'A test needs consistent terms, suitable allocation, economics and a predeclared decision rule.', 'Write an offer-test brief: population, variants, allocation, primary outcome, margin guardrail, run length and inconclusive rule. Use a simulated dataset if no real pilot exists.', 'Offer and price changes are disentangled or interpretation narrowed; no unapproved spend; analysis matches allocation.', 'Compare a packaging change against a price-only change.'],
    ['capstone', 'Recommend a pricing decision', ['test'], 'Combine customer value and economics without overstating what small samples can establish.', 'Present a new product’s package and pricing recommendation, model, evidence gaps and experiment to an operator. Revise after their cost and demand objections.', 'Model reconciles; evidence supports chosen range; sensitivity and external review included.', 'Revisit after customer behaviour is observed and explain forecast errors.'],
  ]),
  tree('copy', 'Copywriting mastery', 'Continue after Copywriting. Research-led persuasion, long-form copy, editing and independently reviewed work.', [
    ['diagnostic', 'Rebuild a persuasive brief', [], 'Entry check: write a customer brief, benefits, proof and CTA without help. If this fails, complete the existing Copywriting tree first.', 'From five sourced customer excerpts, write one reader, buying trigger, alternative, offer, desired action and five objections. Identify awareness and evidence gaps.', 'Claims traceable; reader specific; alternatives and objections grounded in evidence; no invented testimonials.', 'Use a reader who does not yet recognise the problem.'],
    ['analyse', 'Reverse-engineer persuasion', ['diagnostic'], 'Analyse the job each sentence performs, then reconstruct the structure without borrowing the wording.', 'Annotate three ads or pages: attention, relevance, mechanism, proof, objection and action. Close them and write a structurally similar piece for a different product.', 'Every annotation explains function; original draft fits its own evidence; visible ads are not assumed profitable.', 'Use a strong example outside your familiar industry.'],
    ['angles', 'Create genuinely different angles', ['analyse'], 'An angle changes the reason to care; a synonym changes only the wording.', 'Generate 25 concepts across outcome, problem, mechanism, objection and comparison. Select five using relevance, credibility and distinctiveness.', 'Five distinct motivations; each has supporting evidence; rejected concepts have reasons.', 'Constrain yourself to proof already available and eliminate hype.'],
    ['specificity', 'Make claims concrete', ['angles'], 'Concrete language makes a claim understandable and falsifiable. Specificity must not exceed evidence.', 'Rewrite 15 vague claims into mechanism, observable outcome and conditions. For five, draft a demonstration that would test the claim.', 'No invented numbers; conditions preserved; reader can explain what would make a claim false.', 'Edit a high-hype competitor page using only verified information.'],
    ['proof', 'Build a proof sequence', ['specificity'], 'Different doubts require different evidence: mechanism, demonstration, third-party validation or limitations.', 'Order five objections by when a reader encounters them. Write one proof block per objection and a case-study outline with baseline, intervention, outcome and caveats.', 'Evidence matches the doubt; causality not overstated; testimonial permission and missing evidence noted.', 'Write for a sceptical technical buyer with no customer testimonials available.'],
    ['longform', 'Write a complete sales argument', ['proof'], 'A longer page needs a coherent argument rather than repeated claims.', 'Write 800–1,200 words from a blank page: lead, problem, mechanism, offer, proof, objections and action. Map every section back to the brief.', 'No unsupported claim or contradictory term; sequence answers the next reasonable question; offer and commitment explicit.', 'Use the same offer for a different awareness level without merely shortening the page.'],
    ['edit', 'Edit for comprehension', ['longform'], 'Separate argument editing from sentence editing. A polished sentence cannot save a missing reason to believe.', 'Cut 25% of the draft; annotate ten changes. Ask three relevant readers to explain offer, benefit, proof and next step without coaching.', 'Essential terms retained; misunderstandings recorded; revisions target observed problems rather than taste alone.', 'After two days rewrite the weakest section without viewing the original.'],
    ['capstone', 'Build an externally reviewed copy portfolio', ['edit'], 'A portfolio shows original drafts, evidence, feedback and revision. Conversion claims require a trustworthy comparison.', 'Produce a page, email and ad for a fresh category. Get a working copywriter or relevant buyer to score clarity, relevance, credibility and action from 0–2; revise every zero.', 'All four dimensions reach 2: clear, evidenced and usable; reviewer and revisions documented; simulation is labelled; no percentile claim from self-ratings.', 'Repeat on three categories over time, then run a properly designed field comparison where feasible.'],
  ]),
  tree('creative', 'Creative strategy & production', 'Continue after Ad creation. Art direction, concepts, scripts, production, creative testing and iteration.', [
    ['diagnostic', 'Diagnose a creative brief', [], 'Entry check: complete an ad brief, a static ad and a captioned video. Use Ad creation first if you need guided foundations.', 'Audit an offer’s audience, buying situation, promise, evidence, placement and destination. Identify three different communication problems an ad might solve.', 'Six brief fields explicit; each problem tied to evidence; no invented winner labels.', 'Use an offer that is hard to demonstrate visually.'],
    ['concepts', 'Develop a concept matrix', ['diagnostic'], 'Generate across motivations and executions so the set explores ideas rather than cosmetic variations.', 'Cross four motivations with four formats: demo, story, comparison and objection. Write 16 one-sentence concepts, then storyboard three.', 'Concepts differ in reason to care and execution; each contains product relevance and supportable proof.', 'Create a new set while banning your first favourite format.'],
    ['direction', 'Control visual hierarchy', ['concepts'], 'Composition, typography, contrast and framing determine what is noticed and understood.', 'Make three layouts for one concept. Test at intended phone size with five-second exposure, then ask what brand, benefit and action viewers recall.', 'Text legible; message recall recorded; design revision addresses the missed element; preferences not mistaken for lift.', 'Adapt to a narrow placement and a large display while retaining identification.'],
    ['scripts', 'Script a visual demonstration', ['concepts'], 'A video script must specify an observable sequence, not just narration.', 'Write a 15-second and a 30-second version with shot, spoken line, on-screen text and proof for each beat. Time both aloud.', 'Timing feasible; demonstration supports claim; captions stand alone; no misleading before/after framing.', 'Write a version with no voiceover and a version with no testimonial.'],
    ['production', 'Capture and edit a usable asset', ['direction', 'scripts'], 'Production quality means the audience can see, hear and understand the intended demonstration.', 'Record the script plus supporting shots; edit captions, pacing, sound and CTA. Inspect focus, audio and the safe areas of the actual placement.', 'No clipped caption or unintelligible audio; asset matches brief; rights to footage/music confirmed for intended use.', 'Rebuild the opening with a different first frame while keeping the rest fixed.'],
    ['testing', 'Separate concept and execution tests', ['production'], 'Testing different concepts explores strategic ideas; changing one execution element can isolate a narrower question.', 'Create one concept-test set and one hook-only set. Write hypotheses, held constants, business outcome, diagnostic metrics and an inconclusive rule.', 'Interpretation matches what varied; retention or click rate alone does not establish profit; allocation and sample limits stated.', 'Analyse a case where the best hook produces the worst purchase rate.'],
    ['iteration', 'Diagnose a creative result', ['testing'], 'Weak results may come from the offer, targeting, placement, creative or measurement. Diagnose the chain before changing everything.', 'Use a real or labelled mock report to trace impressions → engagement → clicks → qualified sales. List three explanations and the next discriminating edit or test.', 'Numbers reconcile; diagnosis admits confounding; next iteration tests a specific uncertainty.', 'Repeat with strong click-through and weak sales, then weak reach and strong conversion.'],
    ['capstone', 'Produce a campaign learning pack', ['iteration'], 'Creative mastery requires repeatable production and defensible learning across contexts.', 'For a new category deliver three concepts, two finished static ads, two videos, a test plan and revision log. Obtain critique from a creative practitioner and a relevant customer.', 'Brief, assets and measurement agree; critiques recorded; at least one substantial revision; outcomes reported honestly.', 'Repeat under a tighter budget and different placement, then compare recurring weaknesses.'],
  ]),
  tree('content', 'Content & organic distribution', 'Editorial strategy, original reporting, social storytelling, distribution and content evaluation.', [
    ['intent', 'Map audience questions', [], 'Start with a researched audience and offer. Useful content answers a real question at a particular moment.', 'Collect 20 sourced questions from customers, communities or search. Group by buying situation and select five where your business has useful evidence.', 'Sources retained; topics match audience needs; selection includes business relevance and ability to contribute.', 'Repeat for an audience unfamiliar with the category.'],
    ['brief', 'Write an editorial brief', ['intent'], 'A brief specifies the question, reader, original contribution, evidence and desired next action.', 'Write briefs for an explainer, comparison and case study. Specify claims to verify, expert input, outline and distribution destination.', 'Each brief answers one question; original contribution explicit; promotional claims separated from reporting.', 'Have another writer identify missing information before drafting.'],
    ['report', 'Create original source material', ['brief'], 'Original observation, interviews or reproducible analysis give content substance beyond rephrasing other articles.', 'Conduct an interview with permission or analyse a public dataset. Extract five traceable findings and two limitations; fact-check quotations and arithmetic.', 'Sources accessible; findings reproducible; claims stay within evidence; no synthetic quotes.', 'Use a second source to challenge the most attractive finding.'],
    ['write', 'Produce a useful article', ['report'], 'Structure should help the reader solve the problem quickly while preserving necessary detail.', 'Write a 700-word article with a concrete answer, example, evidence and next action. Ask two target readers to complete the intended task using it.', 'Task outcome recorded; sources linked; no empty introduction; revision fixes a real comprehension gap.', 'Write a comparison without favouring your product on unsupported criteria.'],
    ['social', 'Adapt a story to social formats', ['write'], 'Repurposing changes delivery for the medium while retaining the evidence and useful idea.', 'Turn one finding into a short video script, carousel and text post. Make each understandable without the original article.', 'Each format has a clear opening and payoff; claims remain accurate; no context-dependent statistic stripped of its denominator.', 'Adapt a technical explanation for a nontechnical audience.'],
    ['distribute', 'Design useful distribution', ['social'], 'Distribution depends on where the intended audience already pays attention and what participation is welcome there.', 'Build a two-week plan for owned, earned and community channels. Write three contextual introductions and specify the audience benefit, destination and tracking.', 'Plan fits channel norms; no mass unsolicited posting; reuse is tailored; ownership and effort feasible.', 'Plan distribution without your largest existing audience channel.'],
    ['evaluate', 'Evaluate a content cohort', ['distribute'], 'A content portfolio should be assessed by purpose and age; reach, qualified visits and assisted outcomes answer different questions.', 'Compare five pieces using age, audience, reach, qualified action and production effort. Decide keep, improve, repurpose or retire with confidence levels.', 'Like-for-like comparisons; attribution limits explicit; no causal claim from correlation alone.', 'Include an old evergreen article and a recent high-reach post with no qualified action.'],
    ['capstone', 'Run an editorial learning cycle', ['evaluate'], 'A repeatable content system turns audience evidence into production, distribution and revision.', 'For a fresh topic produce one original article and three adaptations, a distribution plan and a result memo. Get editorial feedback and revise the weakest asset.', 'Original evidence, audience task and distribution align; real or simulated outcomes labelled; critique and revision retained.', 'Repeat monthly and track recurring defects per finished piece, not just publication volume.'],
  ]),
  tree('seo', 'SEO & discoverability', 'Search intent, useful pages, technical discovery, internal links, local search and search measurement.', [
    ['intent', 'Classify search intent', [], 'Search optimisation begins with the task behind the query. Use the Resources guide for current platform details.', 'Collect 20 relevant queries. Inspect results and classify task, expected page format, audience and business relevance. Save observation dates.', 'Classifications supported by actual results; volume estimates are not treated as demand certainty.', 'Repeat for ambiguous and local-intent queries.'],
    ['map', 'Map queries to pages', ['intent'], 'Several queries may share a task; making a page per phrase can create duplication rather than usefulness.', 'Group queries into five tasks and assign one primary page per task. Identify gaps and competing pages on a small site.', 'Mapping explains intent overlap; every proposed page has a distinct purpose; existing useful pages retained.', 'Resolve two pages competing to answer the same question.'],
    ['page', 'Build a useful search page', ['map'], 'A page needs a clear answer, evidence and a usable structure. Search engines do not guarantee rankings for following a checklist.', 'Draft one page with descriptive title, headings, direct answer, original example, sources and relevant internal links. Test whether a reader can solve the query task.', 'Page satisfies the task; no keyword stuffing; title accurately describes content; links help navigation.', 'Adapt the page to a comparison query without duplicating the original.'],
    ['technical', 'Diagnose crawling and indexing', ['map'], 'Discovery, crawl access, indexing and ranking are different stages. Fix the stage that is actually failing.', 'On an authorised site or local fixture inspect status code, robots directives, canonical, sitemap and rendered content for five URLs. Record expected versus observed.', 'Can distinguish blocked crawling from noindex and canonicalisation; each proposed fix has evidence.', 'Use a duplicate URL, a removed page and a JavaScript-rendered page.'],
    ['links', 'Improve information architecture', ['page', 'technical'], 'Internal links and clear hierarchy help people and crawlers find related pages.', 'Map a ten-page site, identify orphan pages and add meaningful navigation paths. Write descriptive anchors and justify redirects for changed URLs.', 'Important pages reachable; links resolve; redirects preserve intent; no invented SEO guarantee.', 'Restructure a growing topic without breaking existing navigation.'],
    ['local', 'Audit local and product discovery', ['technical'], 'Discovery also happens through local listings, product feeds and marketplaces; accurate availability matters.', 'Audit business details or five product listings for consistency, category, image, price, stock and destination. Compare with current official platform requirements.', 'Discrepancies documented; fixes address user-facing accuracy; review or rating manipulation excluded.', 'Compare an online-only seller and a physical service business.'],
    ['measurement', 'Read search performance', ['links', 'local'], 'Impressions, clicks, query mix and conversions can move differently. Seasonality and result changes confound simple before/after comparisons.', 'Analyse a dated Search Console export or labelled mock table by query and page. Diagnose three changes and propose checks before assigning causes.', 'Rates calculated correctly; branded and nonbranded demand distinguished where possible; uncertainty preserved.', 'Investigate clicks falling while average position improves because query mix changed.'],
    ['capstone', 'Deliver a prioritised SEO project', ['measurement'], 'An SEO project combines user usefulness with technical discovery and measured follow-through.', 'Audit a fresh small site, implement or prototype three justified fixes, and write expected outcomes, measurement window and limitations for review.', 'Before/after evidence retained; changes solve observed issues; reviewer can reproduce audit; rankings not promised.', 'Review after sufficient indexing time and distinguish implementation success from business impact.'],
  ]),
  tree('search-ads', 'Paid search & shopping', 'Search campaigns, query control, feed quality, bidding economics and budget decisions.', [
    ['economics', 'Set an acquisition constraint', [], 'Complete foundation CAC and margin calculations first. A bid strategy optimises the signal supplied to it.', 'Calculate affordable CPA for three products from net contribution and required profit. Define the conversion, value and excluded low-quality actions.', 'All costs explicit; business outcome distinct from clicks; assumptions survive a sensitivity check.', 'Use a lead-based business with only one in five leads becoming customers.'],
    ['queries', 'Build an intent and query map', ['economics'], 'A keyword is a targeting input; a search term is what someone actually searched. Match behaviour must be checked in current docs.', 'Classify 30 queries as relevant, ambiguous or irrelevant. Propose tightly reasoned groups, landing pages and negatives.', 'No valuable intent excluded accidentally; negative choices explained; branded demand separated for analysis.', 'Audit a query report containing expensive irrelevant and low-volume valuable terms.'],
    ['ads', 'Write a coherent search ad set', ['queries'], 'Each possible asset combination should accurately describe the offer and lead to a matching page.', 'Write headline and description assets for two groups using current limits. Check combinations for repetition, contradictions, unsupported claims and destination mismatch.', 'Assets fit current requirements; every combination remains truthful; query, promise and page align.', 'Write for an unfamiliar category with limited proof.'],
    ['feed', 'Repair a product feed', ['economics'], 'Shopping depends on accurate product data and matching destinations as well as bidding.', 'Audit a mock feed of ten products for identifier, title, image, price, availability and destination consistency. Explain which errors block usefulness.', 'Every mismatch identified; proposed titles describe products accurately; stock and price agree with destination.', 'Add variants and identify where a parent/variant mapping goes wrong.'],
    ['tracking', 'Verify conversion measurement', ['ads', 'feed'], 'Duplicate, missing or wrongly valued conversions can make optimisation pursue the wrong outcome.', 'Write a test plan for a conversion event: normal completion, refresh, cancellation, duplicate transaction and consent state. Use test data and record expected events.', 'Only valid outcomes counted; value/currency consistent; duplicate prevention and failure cases included.', 'Reconcile ad-platform conversions with order or CRM records and explain discrepancies.'],
    ['bidding', 'Diagnose a bidding decision', ['tracking'], 'Average returns conceal marginal returns. Automation still needs good signals and enough relevant evidence.', 'Compare three budget levels using spend, incremental orders and contribution. Write a scale, hold or reduce decision with lag and uncertainty considered.', 'Decision uses marginal contribution; recent conversions allowed to mature; no universal optimal bid rule.', 'Repeat when reported ROAS rises because branded queries take a larger share.'],
    ['capstone', 'Build an auditable search campaign', ['bidding'], 'Campaign skill is demonstrated through coherent setup and decision quality, not an exam badge alone.', 'Create a draft campaign or spreadsheet specification with query map, assets, feed checks, tracking QA, budget ceiling and review plan. Get a practitioner to find errors.', 'Another person can implement the specification; critique corrected; no live spend needed; assumptions and stop conditions explicit.', 'Run a permitted pilot when available and write a decision memo including inconclusive evidence.'],
  ]),
  tree('paid-media', 'Paid social & media buying', 'Audience strategy, campaign structure, signal quality, creative allocation and incremental returns.', [
    ['plan', 'Choose a channel for a reason', [], 'Use foundations economics and Ad creation first. A popular channel may not fit the audience, offer or buying cycle.', 'Compare social, video, display and offline options for one business using audience access, creative needs, buying cycle, cost uncertainty and measurement.', 'Choice tied to a buying situation; alternatives considered; no invented cost benchmark.', 'Use a B2B offer with a long sales cycle.'],
    ['audience', 'Design an audience hypothesis', ['plan'], 'Audience inputs and exclusions should reflect a testable idea. Narrow targeting does not automatically create relevance.', 'Write broad and focused audience hypotheses, exclusions, placement choices and expected trade-offs. Explain how customer overlap affects interpretation.', 'Hypotheses falsifiable; overlapping audiences considered; sensitive or speculative personal inference avoided.', 'Design for a new market with no customer list.'],
    ['structure', 'Specify campaign structure', ['audience'], 'A structure should support the outcome and learning question without fragmenting evidence unnecessarily.', 'Draw campaign, allocation and creative structure for one objective. Define event, naming, budget ceiling, destination and current platform settings to verify.', 'Structure matches the question; no unintended shared budget confound; account-specific settings marked for verification.', 'Simplify a fragmented mock account while preserving the important comparison.'],
    ['signals', 'Audit optimisation signals', ['structure'], 'The platform can only optimise the outcome and value it can observe; signal quality matters more than a neat report.', 'Design tests for browser/server duplicates, missing events, wrong values and qualified versus unqualified leads. Reconcile a mock event log with ten orders.', 'Ten orders reconcile; duplicates and missing events detected; attribution windows and consent limits documented.', 'Repeat for offline closed-won CRM events with delayed outcomes.'],
    ['creative', 'Allocate a creative test', ['signals'], 'A fair creative comparison needs suitable allocation, consistent definitions and room for an inconclusive result.', 'Specify a concept comparison, primary business metric, diagnostic metrics, allocation unit, budget and stopping rule. Explain limits of algorithmically uneven delivery.', 'No winner declared solely from unequal raw totals; confounds explicit; sample adequacy and conversion lag considered.', 'Analyse a low-spend variant with high apparent return and wide uncertainty.'],
    ['scale', 'Evaluate scaling and fatigue', ['creative'], 'Changing performance can reflect saturation, seasonality, auction pressure, signal changes or the offer.', 'Given a four-week mock report, produce three competing explanations for rising CPA and a discriminating check for each. Propose the next budget step.', 'Marginal economics and lag considered; frequency alone does not prove fatigue; proposed change follows evidence.', 'Repeat where CPA improves but total incremental contribution falls.'],
    ['capstone', 'Defend a media investment', ['scale'], 'Good buying combines creative judgement, reliable measurement and economic discipline.', 'Deliver a new-category media plan, setup specification, creative matrix and scenario model. Have a practitioner critique it; write a revised investment memo.', 'Budget reconciles; stop conditions and incremental measurement included; external critique preserved; spend only in an authorised pilot.', 'Compare pilot outcomes with the forecast and record the largest calibration error.'],
  ]),
  tree('cro', 'Conversion & customer experience', 'Funnel diagnosis, usability, landing pages, forms, checkout and controlled optimisation.', [
    ['funnel', 'Locate conversion friction', [], 'Begin with foundation rate calculations. Aggregate conversion hides differences in intent, device and stage.', 'Map a journey from entry to completed value. Calculate stage rates for mobile and desktop using a mock or real table; list missing information.', 'Denominators and time windows consistent; bottleneck not inferred solely from the largest percentage drop.', 'Use high-intent and low-intent acquisition cohorts.'],
    ['test', 'Run a neutral usability task', ['funnel'], 'Qualitative usability work finds problems; a small pilot cannot estimate a population conversion uplift.', 'Write three realistic tasks. Observe willing users attempting them on a prototype without coaching. Record completion, confusion and workarounds.', 'Tasks do not reveal the route; observations factual; severity based on task impact; findings not treated as prevalence.', 'Retest the revised flow with new participants.'],
    ['page', 'Match promise and page', ['test'], 'A landing page should continue the promise that brought the visitor and answer their next questions.', 'Create a mobile wireframe with offer, mechanism, proof, terms and action. Compare its language with the originating ad or query.', 'Promise consistent; essential information visible; a reader explains offer and commitment accurately.', 'Design for a visitor who already knows the product rather than repeating introductory content.'],
    ['forms', 'Reduce form and checkout errors', ['test'], 'Friction reduction includes clear labels, useful errors and recovery, not just removing every field.', 'Prototype a form and checkout with empty, invalid, duplicate and interrupted states. Have someone complete and recover from each task.', 'Required fields justified; errors explain repair; values retained on recoverable failure; mobile interaction usable.', 'Repeat with a slow connection and a keyboard-only walkthrough.'],
    ['hypothesis', 'Prioritise conversion hypotheses', ['page', 'forms'], 'A useful hypothesis names a specific obstacle, change and predicted behavioural effect.', 'Turn five observations into hypotheses. Rank by expected contribution, evidence and effort, then identify what would falsify the top choice.', 'Each change tied to an observation; ranking uncertainty visible; no generic “make the button pop” recommendation.', 'Select a different priority when traffic is too low for a useful A/B test.'],
    ['experiment', 'Predeclare a conversion experiment', ['hypothesis'], 'Randomisation and trustworthy measurement are prerequisites for a causal A/B interpretation. Complete the experimentation tree for analysis depth.', 'Specify allocation unit, primary metric, guardrails, minimum useful effect, sample plan, fixed stopping rule and exclusions. Include sample-ratio and instrumentation checks.', 'Plan permits inconclusive results; no repeated peeking decision rule; multiple outcomes not cherry-picked.', 'Design a repeated-user experiment and explain contamination risks.'],
    ['capstone', 'Deliver a conversion case study', ['experiment'], 'Document the diagnosed problem, evidence, change and limitations before claiming improvement.', 'For a fresh flow, deliver research notes, prototype, experiment plan and result interpretation. Obtain UX and business critique; revise.', 'Design addresses observed friction; statistics and qualitative evidence kept distinct; negative results retained.', 'Revisit on a different device and acquisition cohort before generalising.'],
  ]),
  tree('lifecycle', 'Lifecycle, email & retention', 'Activation, CRM segments, messaging, deliverability, retention cohorts and lifecycle experiments.', [
    ['journey', 'Define activation and retention', [], 'Use foundation metrics first. Activation should represent experienced value; retention needs a meaningful repeat behaviour and interval.', 'Map signup, first value, repeat value, risk and churn. Define one measurable event for each with inclusion rules.', 'Events reflect customer value; churn window fits the product; definitions reproducible.', 'Compare a weekly app with an infrequently purchased service.'],
    ['segments', 'Build lifecycle segments', ['journey'], 'Segments need entry and exit rules so people receive relevant messages and can leave a sequence.', 'Using ten mock contacts, define new, activated, at-risk and inactive groups. Work through overlapping conditions, missing values and unsubscribe status.', 'Every contact assigned predictably; suppression overrides promotion; transitions explicit.', 'Add a reactivated customer and an already-converted contact.'],
    ['sequence', 'Write a lifecycle sequence', ['segments'], 'A sequence helps a customer reach value; each message needs a reason to exist and a stop condition.', 'Write a three-message onboarding sequence with trigger, timing, customer task, evidence, CTA and exit. Draft subject and preview text together.', 'Messages match stage; no contradictory promises; converted or opted-out users stop receiving promotion.', 'Write a renewal or win-back sequence without fake urgency.'],
    ['delivery', 'Plan email quality checks', ['sequence'], 'Delivery and readability are operational skills. Check current sender requirements in the provider’s documentation before setup.', 'Prepare a test-send checklist for authentication, permission, suppression, plain text, links, mobile rendering, accessibility and reply handling. Test only addresses you control.', 'Checklist covers failure states; broken links caught; no purchased-list growth assumed; current docs dated.', 'Inject a wrong personalisation field and a broken destination into a test template.'],
    ['cohorts', 'Calculate retention by cohort', ['journey'], 'Cohorts compare people starting at the same time. An average can hide changes in acquisition quality or product experience.', 'For cohorts of 100 and 200 customers with 40 and 60 returning next month, calculate cohort and combined retention. Explain why comparing only retained counts misleads.', 'Answers: 40%, 30%, 33.3%; starting populations and return definition clear; incomplete cohorts excluded from like-for-like comparisons.', 'Add revenue retention and distinguish expansion from customer retention.'],
    ['test', 'Measure lifecycle incrementality', ['delivery', 'cohorts'], 'People who open or click may already be more engaged. A holdout helps estimate whether the message changed behaviour.', 'Design an eligible-customer holdout with assignment, success event, unsubscribe guardrail and duration. Analyse mock results including confidence limits.', 'Intention-to-treat population preserved; opens not treated as reliable proof of value; attribution separated from causation.', 'Test an onboarding sequence while preventing contamination from other messages.'],
    ['capstone', 'Build a lifecycle programme', ['test'], 'Lifecycle work combines customer value, accurate segmentation, message quality and measurement.', 'For a fresh product deliver event map, segment rules, sequence, QA checklist and holdout plan. Ask an operator to test five edge-case contacts.', 'Rules pass all five cases; content supports value; quality checks and corrections documented.', 'Review after a full customer cycle and revise based on retained value rather than send volume.'],
  ]),
  tree('analytics', 'Marketing analytics & experimentation', 'Data quality, spreadsheets/SQL, uncertainty, A/B tests, attribution, incrementality and modelling.', [
    ['data', 'Audit a marketing dataset', [], 'Start with Marketing foundations rates and economics. Before interpreting a table, establish what one row and one outcome mean.', 'Create or inspect 30 rows of campaign, session and order data. Identify duplicates, missing values, time zones, currency and refunds. Write a data dictionary.', 'Row grain explicit; five checks reproducible; cleaning decisions preserve the original data.', 'Include duplicate transaction IDs and mixed currencies.'],
    ['query', 'Reconcile a funnel with joins', ['data'], 'Joining one-to-many tables can multiply totals. Calculate at the correct grain before aggregation.', 'Use a spreadsheet or SQL to join sessions and orders, count distinct customers and reconcile revenue. Include a customer with two sessions and two orders.', 'Totals match hand-worked cases; no inflated revenue; left-out records explained.', 'Add a refund and an order with no attributable session.'],
    ['uncertainty', 'Quantify uncertainty', ['query'], 'A sample rate is an estimate. Small samples can produce dramatic-looking differences by chance.', 'Compare 20/100 and 200/1,000 conversions. Compute standard errors sqrt(p(1-p)/n) and rough 95% intervals; explain their assumptions.', 'Both rates 20%; SE about 4 and 1.26 percentage points; rough intervals 12.2–27.8% and 17.5–22.5%; approximation limitations acknowledged.', 'Use very small counts and explain why this normal approximation becomes unreliable.'],
    ['design', 'Design a trustworthy A/B test', ['uncertainty'], 'Choose the decision, allocation unit, useful effect and analysis before collecting results.', 'Write a test plan with random assignment, baseline, minimum useful effect, sample-size calculation inputs, primary metric, guardrails, exclusions and stopping rule.', 'Power assumptions explicit; sample plan reproducible with a stated calculator or script; no stopping at first significance; repeated users handled.', 'Plan a cluster-randomised test and identify why individual-level standard errors may fail.'],
    ['analyse', 'Interpret an experimental result', ['design'], 'Statistical evidence, practical value and instrumentation validity are separate checks.', 'Analyse control 200/2,000 and treatment 240/2,000. Calculate absolute and relative lift, rough difference interval, and a decision given a 3-point minimum useful effect.', 'Lift 2 points/20%; rough 95% difference interval about 0.06–3.94 points; the estimate does not establish at least a 3-point improvement; sample ratio and guardrails checked.', 'Repeat with a negative result and with an allocation mismatch that invalidates a simple readout.'],
    ['causal', 'Separate attribution from incrementality', ['analyse'], 'Attribution allocates credit among observed touchpoints; incrementality asks what would have happened without the intervention.', 'Construct a case where retargeting claims 100 sales but a valid holdout implies only 10 additional sales. Calculate attributed and incremental ROAS at $50/order and $500 spend.', 'Answers: 10x versus 1x revenue ROAS; contribution still considered; validity depends on holdout design, contamination and uncertainty.', 'Compare branded search attribution with a geographic or customer holdout.'],
    ['models', 'Critique a marketing model', ['causal'], 'A predictive model or marketing-mix model can fit history while misrepresenting causes. Time effects, collinearity and assumptions matter.', 'Read the measurement paper in Resources. Draw spend, seasonality, price, distribution and demand relationships. List omitted variables and a holdout or sensitivity check.', 'Causal and predictive goals distinguished; no causal claim from fit alone; uncertainty and calibration to experiments discussed.', 'Explain why correlated channel budgets make their separate effects hard to identify.'],
    ['capstone', 'Produce a reproducible decision analysis', ['models'], 'A strong analysis lets someone reproduce the result and see which assumptions could reverse the decision.', 'Package a fresh dataset or labelled simulation, data dictionary, reproducible calculations, experiment critique and one-page decision memo. Have another analyst rerun it.', 'Rerun matches; arithmetic and population definitions reconcile; uncertainty, negative findings and reviewer corrections included.', 'Return to the forecast after a real outcome and score your calibration.'],
  ]),
  tree('partnerships', 'Partnerships, PR & community', 'Channel partnerships, creator briefs, earned media, events, community and reputation.', [
    ['fit', 'Map partner incentives', [], 'A partnership must create value for the audience and both organisations. Start with a clear offer and customer.', 'Compare five possible partners on audience overlap, complementary value, incentive, operational cost and conflict. Select one with an evidence-based rationale.', 'Mutual benefit concrete; overlap not assumed from follower count; alternatives and risks explicit.', 'Compare a reseller, creator and complementary software partner.'],
    ['proposal', 'Write a partnership proposal', ['fit'], 'A useful proposal makes the joint work, responsibilities and value easy to evaluate.', 'Draft a one-page proposal with audience benefit, deliverable, division of work, economics, measurement and exit. Role-play objections with a peer.', 'No vague “exposure” bargain; costs and ownership clear; revision addresses a real objection.', 'Rework for a partner with greater negotiating power.'],
    ['creators', 'Brief a creator collaboration', ['proposal'], 'A creator needs room to communicate credibly within a truthful brief and agreed usage boundaries.', 'Prepare a brief covering audience, product evidence, creative freedom, deliverables, approvals, usage permission, disclosure checks and performance interpretation.', 'Claims supportable; rights and disclosure responsibilities explicit; tracking does not imply causal lift.', 'Design a comparison across creators without treating follower count as equivalent reach.'],
    ['press', 'Develop an earned-media story', ['fit'], 'A story needs news value and verifiable evidence for a particular audience. Promotional enthusiasm is insufficient.', 'Identify three relevant publications and explain fit. Draft a 150-word pitch and evidence pack for one original finding. Keep it as a draft for critique.', 'Pitch contains a clear finding, relevance and evidence; no fabricated exclusivity or quotes; reviewer can verify facts.', 'Find a story in an operational change rather than a product announcement.'],
    ['community', 'Design a community ritual', ['fit'], 'A community should offer member value and healthy participation beyond recurring promotion.', 'Design one recurring activity with member benefit, facilitation, moderation, escalation and success criteria. Run a small invited pilot or tabletop exercise.', 'Activity useful without buying; moderator decisions clear; participation quality assessed beyond membership count.', 'Handle a complaint and a disruptive participant in a role-play.'],
    ['events', 'Model an event or referral programme', ['proposal', 'community'], 'Acquisition programmes need full costs, quality measures and follow-through; registrations alone do not prove return.', 'Model an event or referral pilot including staff time, incentives, qualified attendance, next actions and contribution scenarios. Identify gaming and cannibalisation.', 'Economics reconcile; rewards do not invite fake activity; follow-up relevant and permission-aware.', 'Compare a small qualified audience with a large unqualified one.'],
    ['crisis', 'Respond to a reputation problem', ['press', 'community'], 'A credible response distinguishes known facts, unknowns, accountability and the next update.', 'Role-play a service failure. Draft a holding statement, stakeholder map and response timeline; have a peer challenge unsupported assurances.', 'No speculation presented as fact; affected people have a useful action; responsibilities and update timing clear.', 'Repeat after new evidence contradicts the first explanation.'],
    ['capstone', 'Deliver a partner or community pilot', ['creators', 'events', 'crisis'], 'A pilot should expose execution and relationship quality as well as acquisition outcomes.', 'Create a fresh pilot proposal, assets, operating plan and measurement report. Ask a relevant operator to critique incentives and feasibility; revise.', 'Audience value, responsibilities, costs and evidence align; no messages or spend required for practice; external critique retained.', 'When a real pilot is available, compare outcomes and partner experience with your expectations.'],
  ]),
  tree('operations', 'Marketing operations & AI', 'Tracking plans, CRM quality, automation, AI evaluation, production systems and handoffs.', [
    ['system', 'Map the marketing data flow', [], 'Start with analytics data quality and lifecycle definitions. An operational system needs clear sources of truth and ownership.', 'Draw lead or order flow from collection to CRM, reporting and follow-up. Identify identifiers, permissions, owners and failure points.', 'Every handoff has an owner; duplicate and missing data paths identified; unnecessary personal data excluded.', 'Map an offline lead entering an online campaign report.'],
    ['events', 'Write a tracking contract', ['system'], 'An event definition is a shared agreement about when something happened and how it is represented.', 'Specify five events with trigger, fields, types, value, deduplication key and examples. Test valid, missing and duplicate fixtures.', 'Another person can implement without guessing; invalid events detected; no sensitive data put in URLs or event names.', 'Version a changed event without silently breaking historical reports.'],
    ['crm', 'Build reliable CRM rules', ['system'], 'A CRM needs lifecycle definitions, deduplication and clear handoff conditions.', 'Create rules for ten mock records covering owner, stage, source, duplicate match and service-level follow-up. Test ambiguous and stale records.', 'Rules produce predictable outcomes; no lead silently dropped; correction path exists.', 'Merge duplicate records while preserving history and consent status.'],
    ['automation', 'Design a recoverable automation', ['events', 'crm'], 'Automation should remain correct when it retries or partially fails.', 'Prototype a workflow using synthetic data. Simulate duplicate trigger, timeout, missing field and downstream failure. Specify retry, suppression and human escalation.', 'No duplicate customer action; failures visible; recovery preserves state; test data stays separate from live contacts.', 'Change a rule and explain how existing in-flight records are treated.'],
    ['ai-brief', 'Specify an AI-assisted task', ['events'], 'Use AI for a defined task with a quality standard. Generated fluency is not evidence of factual correctness.', 'Choose a task such as classifying feedback or drafting variants. Write input, context, constraints, output format, examples and a human-reviewed baseline.', 'Task bounded; source evidence supplied; private data handled deliberately; baseline exists before optimisation.', 'Try the same task without examples and compare errors rather than impressions.'],
    ['eval', 'Evaluate AI outputs blindly', ['ai-brief'], 'An evaluation needs unseen cases and a rubric that reflects the real task. The same model praising itself is weak validation.', 'Build 20 held-out examples including ambiguous and adversarial cases. Blindly score baseline and AI output for accuracy, usefulness and unsupported claims; record time and cost.', 'Prompt-development cases excluded; factual claims checked against sources; critical errors reported separately from average score.', 'Rerun after changing the prompt or model and retain the losing results.'],
    ['handoff', 'Write an executable operating procedure', ['automation', 'eval'], 'A procedure is usable when another person can complete the work and recover from predictable errors.', 'Write one production SOP with input, steps, quality checks, exception handling and owner. Have someone follow it without coaching; record every question.', 'Independent run completes; questions produce corrections; AI approval is not substituted for final factual review.', 'Run with a new teammate or unfamiliar dataset.'],
    ['capstone', 'Deliver a reliable marketing workflow', ['handoff'], 'Operational skill means producing correct work repeatedly, including when systems fail.', 'For a fresh use case deliver tracking contract, workflow, test fixtures, AI evaluation if relevant and handoff. Get an operator to inject three failures.', 'Failures detected and recovered; no duplicate external action; before/after quality and active time reported; reviewer can reproduce.', 'Run again after a delay with changed inputs and compare defect rate.'],
  ]),
  tree('leadership', 'Marketing strategy & leadership', 'Integrate the specialist trees through forecasts, budgets, distribution, management and field evidence.', [
    ['diagnosis', 'Build an integrated diagnosis', [], 'Entry check: bring reviewed work from research, positioning, economics, creative and analytics. Missing evidence means returning to that branch, not bluffing a strategy.', 'Write a two-page diagnosis linking customer, competition, capabilities, channels and economics. Identify one binding constraint and three plausible alternatives.', 'Five areas evidenced; no channel-first prescription; falsifying evidence named.', 'Diagnose a business in a different category without borrowing the first strategy.'],
    ['forecast', 'Forecast a marketing outcome', ['diagnosis'], 'A forecast exposes assumptions and can be scored later. Ranges are more honest than false precision.', 'Build downside, base and upside forecasts with acquisition, conversion, retention, margin and capacity assumptions. Name leading indicators that would change the forecast.', 'Model reconciles; assumptions traceable; ranges coherent; outcome date and update rule fixed.', 'After outcomes arrive, record signed error and which assumption caused it.'],
    ['budget', 'Allocate a constrained budget', ['forecast'], 'Allocate across customer access, product experience, brand and activation according to the diagnosed constraint and marginal economics.', 'Allocate a mock $10,000 budget across three justified investments, research and contingency. Compare the next dollar in each option and show a half-budget plan.', 'Totals reconcile; capacity and uncertainty included; no fixed universal channel split; rejected options explained.', 'Reallocate after one channel underperforms and another reaches capacity.'],
    ['distribution', 'Design a route to market', ['diagnosis'], 'Distribution choices change access, margin, control and partner incentives. They are marketing decisions, not just logistics.', 'Compare direct, marketplace, reseller and physical distribution for one offer. Model margins, coverage, conflict and customer experience.', 'Full channel costs included; incentives considered; access benefit supported; conflicts have an operating response.', 'Adapt to a new geography using local evidence and a qualified reviewer rather than literal translation.'],
    ['team', 'Manage creative and analytical work', ['budget', 'distribution'], 'Management improves output through clear briefs, useful feedback, realistic capacity and accountability.', 'Write a team plan with responsibilities, milestones and quality rubrics. Review one weak creative asset and one weak analysis: identify the defect, evidence and next action.', 'Feedback actionable; no taste-only judgement presented as fact; workload feasible; decision owner clear.', 'Role-play disagreement between a creative lead and analyst and document a testable resolution.'],
    ['portfolio', 'Defend a portfolio of decisions', ['team'], 'A professional portfolio should include unsuccessful work and explain decisions using the evidence available at the time.', 'Assemble three category case studies with brief, original output, economics, feedback, revisions and results. Ask an experienced marketer to challenge the weakest case.', 'Results distinguished from simulations; contribution claims proportional to evidence; recurring weaknesses translated into drills.', 'Remove your most polished case and defend the remaining two.'],
    ['capstone', 'Run a complete field learning cycle', ['portfolio'], 'Elite performance requires sustained external results and judgement; completing a curriculum cannot certify a percentile.', 'With an authorised real business, predeclare a bounded intervention and measurement plan, execute, collect outcomes and write a postmortem with the owner. If access is unavailable, do a labelled simulation and leave field validation outstanding.', 'Owner confirms execution; costs and outcomes documented; uncertainty and counterfactual limits explicit; independent review completed; next practice target follows the largest error.', 'Repeat across several business cycles and categories, increasing responsibility only as evidence supports it.'],
  ]),
];

// Suggested cross-tree sequence. Within-tree prerequisites are enforced by the
// existing engine; these preparation links are recommendations, not hidden locks.
export const MARKETING_TREE_ORDER = [
  'Marketing foundations', 'Marketing research', 'Positioning & go-to-market',
  'Brand & consumer behaviour', 'Offers & pricing', 'Copywriting', 'Copywriting mastery',
  'Ad creation', 'Creative strategy & production', 'Marketing analytics & experimentation',
  'Content & organic distribution', 'SEO & discoverability', 'Conversion & customer experience',
  'Paid search & shopping', 'Paid social & media buying', 'Lifecycle, email & retention',
  'Partnerships, PR & community', 'Marketing operations & AI', 'Marketing strategy & leadership',
];

export const MARKETING_PREPARATION: Record<string, string[]> = {
  'Marketing foundations': [],
  'Marketing research': ['Marketing foundations'],
  'Positioning & go-to-market': ['Marketing research'],
  'Brand & consumer behaviour': ['Marketing research'],
  'Offers & pricing': ['Marketing foundations', 'Marketing research'],
  'Copywriting mastery': ['Copywriting', 'Marketing research'],
  'Creative strategy & production': ['Ad creation', 'Copywriting'],
  'Content & organic distribution': ['Marketing research', 'Copywriting'],
  'SEO & discoverability': ['Content & organic distribution'],
  'Paid search & shopping': ['Offers & pricing', 'Marketing analytics & experimentation'],
  'Paid social & media buying': ['Ad creation', 'Marketing analytics & experimentation'],
  'Conversion & customer experience': ['Copywriting', 'Marketing analytics & experimentation'],
  'Lifecycle, email & retention': ['Copywriting', 'Marketing foundations'],
  'Marketing analytics & experimentation': ['Marketing foundations'],
  'Partnerships, PR & community': ['Positioning & go-to-market'],
  'Marketing operations & AI': ['Marketing analytics & experimentation', 'Lifecycle, email & retention'],
  'Marketing strategy & leadership': ['Positioning & go-to-market', 'Offers & pricing', 'Creative strategy & production', 'Marketing analytics & experimentation'],
};

const resource = (title: string, url: string, when: string): Resource => ({ title, url, when });
const mit = (when: string) => resource('MIT OpenCourseWare · Marketing Management', 'https://ocw.mit.edu/courses/15-810-marketing-management-fall-2010/pages/syllabus/', when);
const research = (when: string) => resource('Nielsen Norman Group · Interview sampling', 'https://www.nngroup.com/articles/interview-sample-size/', when);
const usability = (when: string) => resource('Nielsen Norman Group · Usability testing', 'https://www.nngroup.com/articles/usability-testing-101/', when);
const positioning = (when: string) => resource('April Dunford · Introduction to positioning', 'https://www.aprildunford.com/post/an-introduction-to-positioning', when);
const creative = (when: string) => resource('Meta Blueprint · Creative Strategy Study Guide', 'https://www.facebookblueprint.com/student/page/210605-creative-strategy-study-guide', when);
const ads = (when: string) => resource('Google Skillshop · Ads learning paths', 'https://skillshop.withgoogle.com/googleads/', when);
const content = (when: string) => resource('HubSpot Academy · Content Marketing', 'https://academy.hubspot.com/courses/content-marketing', when);
const email = (when: string) => resource('HubSpot Academy · Email Marketing', 'https://academy.hubspot.com/courses/email-marketing-certification-en', when);
const experiments = (when: string) => resource('Kohavi et al. · Online Controlled Experiments and A/B Tests', 'https://exp-platform.com/Documents/2023-03-11EncyclopeiaMLDSABTestingFinal.pdf', when);
const measurement = (when: string) => resource('Google · Media Effectiveness Guide', 'https://www.thinkwithgoogle.com/_qs/documents/18494/UPDATED_TwG_CMO_CFO_Media_Effectiveness_Guide.pdf', when);

export const MARKETING_RESOURCES: Record<string, Resource[]> = {
  'Marketing foundations': [mit('Value → diagnosis: use the syllabus and lecture notes to distinguish customer, product, price, promotion and distribution decisions. Reconstruct your own case after reading.')],
  'Marketing research': [research('Recruitment → interviews → surveys: read about sampling and saturation before writing your screener. Practise on real past decisions; do not treat a few interviews as market percentages.'), usability('Observation → synthesis: learn task-based observation, then conduct and code a neutral task session.')],
  'Positioning & go-to-market': [positioning('Alternatives → value → target → positioning: apply the five components to your own evidence, then test whether a buyer understands the result.'), resource('HubSpot Academy · Inbound Sales', 'https://academy.hubspot.com/courses/inbound-sales', 'Message → enablement: study exploration and advice, then role-play discovery and a buying decision.'), mit('Launch → capstone: connect the positioning choice to product, channel and economics.')],
  'Brand & consumer behaviour': [resource('Ehrenberg-Bass · How B2B Brands Grow', 'https://sponsors.marketingscience.info/wp-content/uploads/sites/2/reports/2023/11/How-B2B-brands-grow.pdf', 'Situations → memory → reach: read the sections on category entry points and growth. Make a falsifiable category diagnosis rather than copying a universal prescription.'), resource('Ehrenberg-Bass · Measuring brand growth', 'https://marketingscience.info/how-do-you-measure-how-brands-grow/', 'Assets → scorecard: distinguish a useful brand measure from an appealing design judgement.'), resource('Ehrenberg-Bass · Easy to Find', 'https://marketingscience.info/news-and-insights/easy-to-find-being-where-b2b-buying-happens', 'Access → capstone: inspect where buyers can actually find and buy the offer.')],
  'Offers & pricing': [resource('MIT · Pricing lecture', 'https://ocw.mit.edu/courses/15-810-marketing-management-analytics-frameworks-and-applications-fall-2015/af93b992c0c358d2957cc8be6710dedb_MIT15_810F15_L10_Pricing.pdf', 'Costs → value → packaging → elasticity: work the numerical cases, close the slides and solve a new case. The old examples teach economics, not current market prices.'), experiments('Promotion → offer test: use randomised comparison principles before interpreting a pricing result.')],
  'Copywriting mastery': [positioning('Brief → angles → specificity: ground the argument in alternatives and differentiated value.'), content('Analysis → long-form → editing: study storytelling and creation, then produce a fresh draft and test comprehension.'), usability('Proof → portfolio: observe whether target readers understand the argument; do not infer conversion lift from preference.')],
  'Creative strategy & production': [creative('Concepts → direction → scripts → production: use the guide as a reference, then create your own assets. Recheck placement requirements before export.'), experiments('Testing → iteration → capstone: match what varied with what you can conclude.')],
  'Content & organic distribution': [content('Questions → brief → reporting → article → adaptation → distribution: take only the lesson needed for the next output; complete the original reporting exercise before repurposing.'), usability('Evaluation → capstone: observe a reader using your content to complete its intended task.')],
  'SEO & discoverability': [resource('Google Search Central · SEO Starter Guide', 'https://developers.google.com/search/docs/fundamentals/seo-starter-guide', 'Intent → page → technical → links: inspect and repair actual examples after each section; use linked current documentation for local/product-specific requirements.'), resource('Google Search Central · Do you need an SEO?', 'https://developers.google.com/search/docs/fundamentals/do-i-need-seo', 'Measurement → capstone: use Search Console and its current guidance to evaluate visibility; keep implementation checks separate from ranking claims.')],
  'Paid search & shopping': [ads('Economics → queries → ads → feed: Search and Shopping paths. Tracking → bidding: Measurement path. Practise in drafts or a spreadsheet before any live budget.'), measurement('Bidding → capstone: reconcile platform credit with business contribution and incremental evidence.')],
  'Paid social & media buying': [creative('Plan → audience → structure → creative: use current Meta Blueprint material and follow its links for current account settings.'), ads('Plan: compare Video and Display learning paths when those channels fit your audience.'), measurement('Signals → allocation → scaling: use attribution and experiments for the different questions they can answer.')],
  'Conversion & customer experience': [usability('Funnel → tasks → pages → forms: learn observation, then conduct small iterative usability sessions.'), experiments('Hypotheses → experiment → case study: read design and trustworthiness sections before claiming causal improvement.')],
  'Lifecycle, email & retention': [email('Journey → segments → sequences → delivery: use segmentation, permissions, design and automation lessons; cohorts → holdout: use analytics and testing lessons, then solve the original drills.'), experiments('Holdout → capstone: compare assigned groups, including people who did not open the email.')],
  'Marketing analytics & experimentation': [resource('Google Analytics · Set up events', 'https://developers.google.com/analytics/devguides/collection/ga4/events', 'Data → queries: connect reporting definitions to events and validate examples before analysing.'), experiments('Uncertainty → design → analysis: read the paper in stages and rebuild each worked example in your own sheet or script.'), measurement('Attribution → models → capstone: compare attribution, incrementality and mix modelling; write which assumptions could invalidate a decision.')],
  'Partnerships, PR & community': [mit('Fit → proposal → events: apply distribution and incentive reasoning to a partner case.'), resource('PRSA · Learn about public relations', 'https://www.prsa.org/prssa/about-prssa/learn-about-pr', 'Press → community → crisis: use the profession’s introduction and linked resources; practise verified statements and stakeholder responses.'), resource('HubSpot Academy · Digital Marketing', 'https://academy.hubspot.com/courses/digital-marketing', 'Creators → distribution: use the relevant social-media sections, then draft a specific collaboration brief.')],
  'Marketing operations & AI': [resource('Google Analytics · Event implementation', 'https://developers.google.com/analytics/devguides/collection/ga4/events', 'System → events: compare your tracking contract with current event definitions and validation tools.'), email('CRM → automation: use contact management and automation lessons, then test synthetic edge cases.'), resource('Google · Datasets, generalisation and overfitting', 'https://developers.google.com/machine-learning/crash-course/overfitting', 'AI task → evaluation: learn why unseen evaluation cases matter, then compare actual outputs with a human-checked baseline. Continue AI foundations & papers for model internals.')],
  'Marketing strategy & leadership': [resource('MIT · Action Learning Assignment', 'https://ocw.mit.edu/courses/15-810-marketing-management-analytics-frameworks-and-applications-fall-2015/pages/assignments/action-learning-assignment/', 'Diagnosis → distribution → portfolio: study the assignment format, then integrate the decisions for your own business case.'), measurement('Forecast → budget: connect expenditure decisions to evidence strength and business outcomes.'), experiments('Field cycle: use a trustworthy comparison where feasible, and state causal limits where it is not.')],
};
