import type { CoreSkillTreeSeed, CoreSkillSeedNode } from './core-skill-seeds';

type Lesson = [key: string, title: string, prerequisites: string[], lesson: string, exercise: string, rubric: string];
const curriculum = (key: string, title: string, description: string, lessons: Lesson[]): CoreSkillTreeSeed => ({
  key, title, description, nodes: lessons.map(([key, title, prerequisiteKeys, description, practicePrompt, successCriteria]): CoreSkillSeedNode => ({ key, title, prerequisiteKeys, description, practicePrompt, successCriteria, dimension: key === 'capstone' ? 'transfer' : 'procedural' })),
});

// Original practice curricula inspired by prerequisite mastery, not official Math Academy courses.
export const PRIORITY_CURRICULA = [
  curriculum('copywriting', 'Copywriting', 'Write persuasive copy from customer evidence. Build a portfolio one short, assessed exercise at a time.', [
    ['brief', 'Write a one-reader brief', [], 'A useful brief identifies one reader, their situation, the offer and one desired action. Use a real product throughout this tree.', 'In 10 minutes, write a 100-word brief for one product: reader, trigger, problem, current alternative and action. Mark assumptions.', 'One specific reader and action; a concrete problem; assumptions explicitly labelled.'],
    ['voice', 'Collect customer language', ['brief'], 'Customer language supplies raw material. Separate verbatim observations from your interpretation; never invent testimonials.', 'Collect five public reviews or interview excerpts. Record source, situation, pain, desired outcome and exact wording.', 'Five traceable excerpts; each has a situation and outcome; no invented quotes.'],
    ['benefits', 'Translate features into benefits', ['brief'], 'A feature matters through what it lets this reader do. Avoid benefits that any competitor could claim.', 'Write ten feature → mechanism → reader outcome chains. Cut unsupported promises and keep the three most specific.', 'Each chain explains how the feature creates the outcome; no unsupported guarantee.'],
    ['offer', 'Build a credible offer', ['voice', 'benefits'], 'An offer connects an outcome, deliverable, terms and credible proof. Urgency must have a real reason.', 'Write a 120-word offer with deliverables, price placeholder, proof, constraints and a single next step.', 'Reader can identify what they get and what they must do; claims have evidence or are removed.'],
    ['headlines', 'Write twenty distinct headlines', ['offer'], 'Headlines select a reader and make the next sentence worth reading. Different words around the same idea are not different angles.', 'Write twenty headlines in 20 minutes across benefit, problem, mechanism and objection angles. Select three and explain the trade-offs.', 'Twenty drafts; at least four angles; chosen headlines are specific, truthful and relevant to the brief.'],
    ['lead', 'Write a lead that earns the next line', ['headlines'], 'The lead connects the headline to a problem the reader recognises, then introduces a plausible route forward.', 'Write three 80-word leads for the same headline. Use a concrete situation, problem or demonstration. Read aloud and cut throat-clearing.', 'Headline promise is continued; reader recognises the situation; no claim outruns evidence.'],
    ['proof', 'Answer objections with proof', ['offer'], 'Proof answers a particular doubt. A demonstration, measured result or specific example is stronger than an unsupported adjective.', 'List five objections. Pair each with available evidence; write a 50-word response. Label evidence still needed.', 'All five objections are answered honestly; missing evidence is visible; limitations are preserved.'],
    ['cta', 'Write a clear call to action', ['proof'], 'The call to action tells the reader exactly what happens next and removes avoidable uncertainty.', 'Write five calls to action including button text and adjacent reassurance for your offer.', 'One action per version; next step and commitment are clear; reassurance is factual.'],
    ['page', 'Assemble a landing page', ['lead', 'proof', 'cta'], 'Sequence information in the order a sceptical reader needs it: relevance, value, proof, concerns, action.', 'Draft a 500-word landing page from a blank page. Include headline, lead, benefits, proof, objections and CTA.', 'All six parts serve one offer; no contradictions; reader can explain offer and action.'],
    ['edit', 'Edit against a fixed rubric', ['page'], 'Editing is a separate repetition: locate a defect, name why it hurts the reader, revise and compare.', 'Cut your page by 20% without losing evidence or terms. Keep before/after versions and annotate five meaningful edits.', 'Five edits improve clarity or credibility; required information survives; no new unsupported claims.'],
    ['capstone', 'Test copy on a new offer', ['edit'], 'Transfer means writing for a different reader without copying your first page. Comprehension evidence is not proof of conversion lift.', 'Write a page for a second offer. Ask three readers to explain it and its next step without coaching. Revise their largest misunderstanding.', 'Three recorded reader responses; an independent draft; one revision tied to observed confusion.'],
  ]),
  curriculum('ad-creation', 'Ad creation', 'Create static and video ads, build useful variations, and learn to interpret a creative test.', [
    ['brief', 'Define an ad brief', [], 'An ad is a bridge from a specific audience situation to one offer and next action.', 'Pick a real offer. Write audience, problem, promise, proof, destination and one conversion event in 100 words.', 'All six are explicit and consistent; success is an action rather than a vague awareness goal.'],
    ['analyse', 'Deconstruct five ads', ['brief'], 'Separate observable creative choices from guesses about performance. A visible ad is not necessarily a winning ad.', 'Collect five ads. Annotate hook, audience cue, promise, proof, visual, CTA and what you cannot know about results.', 'Five complete breakdowns; performance claims are not inferred from visibility.'],
    ['angles', 'Generate distinct creative angles', ['analyse'], 'An angle changes the reason someone should care: problem, benefit, demonstration, comparison or objection.', 'Write twelve concepts across four angles for the same offer. Each gets a hook, proof idea and CTA.', 'Four meaningfully different reasons to care; each supported by plausible, honest proof.'],
    ['hooks', 'Produce hooks for one angle', ['angles'], 'The opening must make the content relevant quickly and deliver on its promise.', 'Write ten opening lines and sketch ten first frames. Pair the best three and explain who each selects.', 'First frame and line reinforce each other; product relevance is clear; no misleading bait.'],
    ['static', 'Design a readable static ad', ['hooks'], 'Hierarchy directs attention to one message. Inspect the actual mobile size, not only a large canvas.', 'Make three static ads with different layouts. View each on your phone for five seconds and test message recall with another person.', 'Offer and CTA are legible; imagery supports the message; tester identifies intended message.'],
    ['script', 'Write a short video script', ['hooks'], 'A usable script specifies both what is seen and what is heard, including a demonstration and next step.', 'Write three 20–30 second scripts: problem/solution, demonstration and objection. Time a spoken read.', 'All fit the target duration; visual directions are shootable; proof and CTA are included.'],
    ['shoot', 'Capture usable footage', ['script'], 'Clear audio, adequate light and relevant demonstration footage matter more than elaborate production.', 'Record one script plus five supporting shots. Listen with headphones and inspect focus before editing.', 'Speech intelligible; subject in focus; all claims supported by what is shown or stated.'],
    ['edit', 'Edit a complete video ad', ['shoot'], 'Every shot must move the message forward. Captions should make sense with sound off.', 'Cut a 20–30 second ad with captions and CTA. Watch once without sound and once at normal phone size.', 'Captions accurate and readable; no dead opening; demonstration and CTA survive both checks.'],
    ['variants', 'Make a controlled variation set', ['static', 'edit'], 'To learn why a change matters, hold the offer, audience and destination steady while changing one creative variable.', 'Create three versions varying only the hook. Name the hypothesis for each and inventory what is held constant.', 'Versions differ only in the declared variable; each prediction can be contradicted by results.'],
    ['measurement', 'Read campaign arithmetic', ['brief'], 'Clicks, conversions and revenue answer different questions. A cheap click can still produce expensive customers.', 'For 10,000 impressions, 200 clicks, 8 purchases, $160 spend and $400 revenue, calculate CTR, CPC, conversion rate, CPA and ROAS. Repeat with new numbers.', 'Answers: 2%, $0.80, 4%, $20 and 2.5×. Denominators correct; ROAS is not profit.'],
    ['test', 'Design a creative experiment', ['variants', 'measurement'], 'Predeclare the decision and avoid calling a winner from a handful of conversions. Use simulation if no campaign budget is authorised.', 'Write a test plan with one variable, allocation, primary metric, duration, spend ceiling and an inconclusive outcome. Analyse a mock result.', 'Plan distinguishes a useful signal from noise; inconclusive results are allowed; no spend required.'],
    ['capstone', 'Deliver a creative learning report', ['test'], 'A portfolio should show the reasoning, finished assets and what the next iteration will test.', 'Package one static ad, one video, three hook variants and a one-page result report using real or clearly labelled simulated data.', 'Assets share one brief; report distinguishes observation from inference; next change addresses evidence.'],
  ]),
  curriculum('ai-foundations', 'AI foundations & papers', 'Understand how models learn, implement small systems, then read foundational papers with reproducible experiments.', [
    ['python', 'Manipulate data in Python', [], 'Start with functions, lists, loops, files and errors. You need to write and debug small programs before training models.', 'From a blank file, read text, count words, return the ten most frequent and test empty input and punctuation.', 'Program runs without copied solution; counts verified on a tiny hand-worked example; edge cases tested.'],
    ['vectors', 'Compute with vectors and matrices', ['python'], 'Vectors represent features; matrix multiplication combines weighted inputs. Track dimensions before computing.', 'Compute a dot product and a 2×3 by 3×2 matrix product by hand, then verify in Python. Explain each resulting shape.', 'Every entry matches; incompatible shapes are recognised; dimensions explained without notes.'],
    ['probability', 'Work with probability and log loss', ['python'], 'Probabilities must sum to one. Log loss penalises confident wrong predictions more than uncertain ones.', 'For target class 1, compute -log(p) at p=0.9, 0.5 and 0.1. Implement normalisation and sample a categorical distribution.', 'Loss ordering correct; probabilities sum to one; observed frequencies approach the intended distribution.'],
    ['gradients', 'Calculate derivatives and gradients', ['vectors'], 'A derivative describes local sensitivity. The chain rule connects an output loss to parameters through intermediate operations.', 'Differentiate (wx+b-y)^2 with respect to w and b. Check your gradients using finite differences at three inputs.', 'Analytic and numerical gradients agree within a stated tolerance; signs and chain rule explained.'],
    ['regression', 'Train a linear model', ['gradients', 'probability'], 'Training changes parameters to reduce training loss. Held-out data tests whether it generalises.', 'Generate noisy linear data, split train/test, implement gradient descent and compare held-out error with a constant baseline.', 'Loss falls; held-out error beats baseline; test data never used for fitting.'],
    ['backprop', 'Build a tiny neural network', ['regression'], 'Compose linear operations and nonlinearities; backpropagation distributes the loss gradient through that graph.', 'Follow the micrograd lesson, then close it and rebuild a small two-layer network. Gradient-check and fit XOR.', 'Can explain forward/backward passes; numerical gradient check passes; XOR predictions correct.'],
    ['tokens', 'Build a bigram language model', ['backprop'], 'Language models predict token distributions. Tokenisation sets the units; sampling differs from choosing the largest probability.', 'Using a small text corpus, build character IDs and a bigram model. Report held-out loss and sample at two temperatures.', 'No train/test overlap; valid probability distributions; explain why fluent fragments do not imply understanding.'],
    ['attention', 'Implement scaled dot-product attention', ['tokens', 'vectors'], 'Queries and keys determine weights; values supply the mixed content. A causal mask prevents access to future tokens.', 'Read Attention Is All You Need section 3.2. Implement QKᵀ/√d, causal masking, softmax and value mixing on a tiny example.', 'Shapes correct; each attention row sums to one; changing future tokens cannot alter earlier outputs.'],
    ['transformer', 'Train a miniature transformer', ['attention'], 'Residual paths, positional information and feed-forward blocks complement attention. Small experiments expose implementation mistakes.', 'Build a tiny character transformer using the Zero to Hero GPT lesson. Rebuild its block from memory and compare held-out loss to your bigram baseline.', 'Causal test passes; loss and compute recorded; baseline comparison reported even if the new model loses.'],
    ['few-shot', 'Read and test few-shot learning', ['transformer'], 'Separate training updates from examples supplied in context. A paper result has a task, metric, baseline and limitation.', 'Read Language Models are Few-Shot Learners: abstract, section 2 and one result. Test zero-shot versus few-shot on twenty fixed examples.', 'One-page paper card states claim, method, evidence and limitation; evaluation examples separate from prompt examples.'],
    ['rag', 'Build retrieval-augmented answers', ['few-shot'], 'Retrieval supplies external evidence at inference time; it does not guarantee that the answer follows the evidence.', 'Read the RAG paper introduction and method. Build retrieval over ten documents, compare answers with and without retrieval on twenty questions.', 'Report retrieval failures and unsupported claims; answers cite passages; unanswerable questions included.'],
    ['alignment', 'Explain instruction tuning and RLHF', ['few-shot'], 'Supervised demonstrations and preference feedback change model behaviour through training. This differs from prompting a frozen model.', 'Read the InstructGPT paper figure 2, methods and limitations. Draw its three training stages from memory and list three failure cases.', 'Distinguish SFT, reward modelling and policy optimisation; explain why preference scores do not prove factual accuracy.'],
    ['capstone', 'Reproduce a small AI experiment', ['rag', 'alignment'], 'Reproduction requires a fixed question, baseline, data split, implementation, metric and honest error analysis.', 'Choose retrieval or few-shot prompting. Run a held-out comparison, save code/data versions and write a two-page report with failures, cost and next experiment.', 'Someone else can rerun the comparison; claims match measured evidence; limitations and negative results retained.'],
  ]),
];

export const CURRICULUM_RESOURCES: Record<string, { title: string; url: string; when: string }[]> = {
  Copywriting: [{ title: 'Copy That! — copywriting lessons', url: 'https://www.copythatshow.com/', when: 'Use a lesson to repair a specific weakness, then write your own version from a fresh brief.' }],
  'Ad creation': [{ title: 'Meta Blueprint', url: 'https://www.facebook.com/business/learn', when: 'Before platform setup: check current creative and measurement guidance. May require sign-in.' }],
  'AI foundations & papers': [
    { title: '3Blue1Brown — neural networks', url: 'https://www.3blue1brown.com/topics/neural-networks', when: 'Gradients and backprop: build intuition, then solve the node exercise without the video.' },
    { title: 'Karpathy — Neural Networks: Zero to Hero', url: 'https://karpathy.ai/zero-to-hero.html', when: 'Backprop → bigrams → transformer: micrograd, makemore, then GPT. Rebuild after each lesson.' },
    { title: 'Attention Is All You Need (2017)', url: 'https://arxiv.org/abs/1706.03762', when: 'After bigrams: section 3 and attention implementation before the miniature transformer.' },
    { title: 'Language Models are Few-Shot Learners (2020)', url: 'https://arxiv.org/abs/2005.14165', when: 'After your transformer: compare zero-shot and few-shot on a fixed evaluation set.' },
    { title: 'Retrieval-Augmented Generation (2020)', url: 'https://arxiv.org/abs/2005.11401', when: 'After few-shot evaluation: reproduce a small retrieval comparison.' },
    { title: 'InstructGPT / human feedback (2022)', url: 'https://arxiv.org/abs/2203.02155', when: 'After few-shot evaluation: reconstruct the training pipeline and its limitations.' },
  ],
};
